export const seedCards = [
  {
    id: 'confirmation-bias',
    order: 1,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Confirmation Bias',
        hook: "You've already decided. Now you're just collecting evidence.",
        body: "Your brain doesn't look for truth — it looks for validation. You notice information that confirms your beliefs and ignore everything that doesn't. It feels like research. It's actually a filter.",
        example: "You think a colleague is incompetent. From now on, every mistake they make stands out. Every success goes unnoticed. You've built a case, not a picture.",
        tip: "Before deciding, spend 5 minutes actively looking for evidence that you're wrong. The discomfort you feel is the bias resisting.",
      },
      ru: {
        title: 'Предвзятость подтверждения',
        hook: 'Ты уже решил. Теперь просто собираешь доказательства.',
        body: 'Мозг ищет не правду — он ищет подтверждение. Ты замечаешь факты, которые совпадают с твоими убеждениями, и фильтруешь всё остальное. Это не исследование. Это самообман с видом исследования.',
        example: 'Ты считаешь коллегу некомпетентным. Теперь каждая его ошибка бросается в глаза. Каждый успех проходит мимо. Ты строишь обвинение, а не картину реальности.',
        tip: 'Перед любым важным решением потрать 5 минут на поиск доказательств, что ты неправ. Дискомфорт, который ты почувствуешь — это и есть предвзятость.',
      },
    },
  },
  {
    id: 'anchoring-effect',
    order: 2,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Anchoring Effect',
        hook: "That price feels reasonable. Only because they showed you a bigger one first.",
        body: "The first number you hear becomes an anchor. Every estimate, negotiation, and judgment you make gets pulled toward it — even if the anchor was chosen at random. You think you're reasoning. You're calibrating.",
        example: "A store marks a jacket 'was $400, now $180'. You feel like you're getting a deal. The original price may have been invented specifically to anchor you at $180.",
        tip: "Ask yourself: if I'd never heard the first number, would this still feel reasonable? If your answer changes — you were anchored.",
      },
      ru: {
        title: 'Эффект якоря',
        hook: 'Цена кажется разумной. Только потому что сначала показали бо́льшую.',
        body: 'Первое число, которое ты услышал, становится якорем. Все дальнейшие оценки притягиваются к нему — даже если якорь был выбран случайно. Тебе кажется, что ты рассуждаешь. На самом деле — калибруешься.',
        example: 'Пальто «было 20 000, теперь 9 000». Ощущение выгодной покупки. Исходная цена могла быть выдумана именно для того, чтобы якорь поставить на 9 000.',
        tip: 'Спроси себя: если бы я не слышал первое число, цена всё равно казалась бы мне нормальной? Если ответ меняется — ты попался.',
      },
    },
  },
  {
    id: 'dunning-kruger',
    order: 3,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Dunning-Kruger Effect',
        hook: "The less you know, the more confident you are.",
        body: "Beginners overestimate their competence because they don't know enough to know what they're missing. Experts underestimate theirs because they're constantly aware of complexity. Confidence and knowledge move in opposite directions — at first.",
        example: "After two weeks of investing, someone is certain they've found a strategy. After twenty years, they're far more cautious. Same domain. Inverted confidence.",
        tip: "When you feel absolutely certain about something complex, treat it as a warning sign — not a green light.",
      },
      ru: {
        title: 'Эффект Даннинга–Крюгера',
        hook: 'Чем меньше знаешь — тем увереннее себя чувствуешь.',
        body: 'Новичок переоценивает себя, потому что не знает, чего не знает. Эксперт недооценивает, потому что видит всю сложность. Уверенность и знание движутся в противоположных направлениях — поначалу.',
        example: 'Через две недели торговли на бирже человек уверен, что нашёл стратегию. Через двадцать лет — он стал намного осторожнее. Та же сфера. Перевёрнутая уверенность.',
        tip: 'Когда чувствуешь абсолютную уверенность в чём-то сложном — это тревожный знак, а не зелёный свет.',
      },
    },
  },
  {
    id: 'survivorship-bias',
    order: 4,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Survivorship Bias',
        hook: "You're learning from the winners. The losers aren't here to talk.",
        body: "We study what survived and ignore what didn't — because failures are invisible. This makes us draw wildly wrong conclusions about what works. Every lesson learned from winners contains a silent, invisible counter-lesson from those who tried the same thing and failed.",
        example: "Startup advice comes almost entirely from founders who succeeded. Thousands tried the same moves and failed. Their stories never became books.",
        tip: "For every success story, ask: what would the failure stories look like? Are they telling a different story?",
      },
      ru: {
        title: 'Ошибка выжившего',
        hook: 'Ты учишься у победителей. Проигравших здесь нет.',
        body: 'Мы изучаем выживших и игнорируем тех, кто не выжил — потому что провалы невидимы. Это заставляет нас делать неверные выводы о том, что работает. Каждый урок победителя содержит молчаливый контрурок тех, кто делал то же самое и провалился.',
        example: 'Советы стартапов почти всегда исходят от основателей, которые преуспели. Тысячи попробовали те же приёмы и потерпели неудачу. Их истории не стали книгами.',
        tip: 'За каждой историей успеха спроси: как выглядят истории провалов? Они говорят что-то другое?',
      },
    },
  },
  {
    id: 'availability-heuristic',
    order: 5,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Availability Heuristic',
        hook: "You think it's more likely because it was on the news.",
        body: "Your brain estimates probability by how easily examples come to mind. Vivid, recent, emotional events feel more common than they are. Boring statistics feel impossible. The more dramatic a scenario, the more dangerous it seems — regardless of actual frequency.",
        example: "After a shark attack makes headlines, beach attendance drops. Car accidents kill vastly more people per week. Nobody cancels road trips.",
        tip: "When estimating risk, look up actual statistics. Your gut is using drama as a proxy for data.",
      },
      ru: {
        title: 'Эвристика доступности',
        hook: 'Это кажется более вероятным, потому что об этом писали в новостях.',
        body: 'Мозг оценивает вероятность по лёгкости, с которой приходят примеры. Яркие, свежие, эмоциональные события кажутся более распространёнными. Скучная статистика — невозможной. Чем драматичнее сценарий, тем он кажется опаснее — вне зависимости от реальной частоты.',
        example: 'После сообщения об атаке акулы посещаемость пляжей падает. ДТП убивают значительно больше людей в неделю. Никто не отменяет поездки на машине.',
        tip: 'Когда оцениваешь риск — найди реальную статистику. Твоя интуиция использует драму вместо данных.',
      },
    },
  },
  {
    id: 'sunk-cost-fallacy',
    order: 6,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Sunk Cost Fallacy',
        hook: "You keep going because you've already put too much in to stop.",
        body: "Money spent, time invested, effort given — none of it should influence future decisions. It's gone either way. But your brain treats past investment as a reason to continue, even when stopping is clearly the better choice.",
        example: "You stay in a job you hate for three years because you've already been there three years. That logic costs you three more.",
        tip: "Ask: if I were starting fresh today, would I choose this? If not, you're not being loyal — you're being held hostage by sunk costs.",
      },
      ru: {
        title: 'Ошибка невозвратных затрат',
        hook: 'Ты продолжаешь, потому что уже слишком много вложил, чтобы остановиться.',
        body: 'Потраченные деньги, вложенное время, приложенные усилия — всё это не должно влиять на будущие решения. Они ушли в любом случае. Но мозг воспринимает прошлые инвестиции как причину продолжать — даже когда остановиться очевидно лучше.',
        example: 'Ты остаёшься на нелюбимой работе три года, потому что уже три года там. Эта логика обходится тебе ещё тремя.',
        tip: 'Спроси: если бы я начинал с нуля сегодня, я бы выбрал это? Если нет — ты не верен себе. Ты в заложниках у прошлых трат.',
      },
    },
  },
  {
    id: 'framing-effect',
    order: 7,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Framing Effect',
        hook: "How something is said changes what you decide. Every single time.",
        body: "Identical information, presented differently, produces different choices. '90% survival rate' and '10% death rate' are mathematically the same. They don't feel the same. Whoever controls the frame controls the decision.",
        example: "Ground beef labeled '80% lean' sells better than '20% fat'. Same product. Different frame. Different behavior.",
        tip: "Restate every important choice in its opposite frame before deciding. If your answer changes, the frame was doing the deciding — not you.",
      },
      ru: {
        title: 'Эффект фрейминга',
        hook: 'То, как сказано, меняет то, что ты решаешь. Каждый раз.',
        body: 'Одинаковая информация, поданная по-разному, приводит к разным выборам. «90% выживших» и «10% смертности» математически идентичны. На ощущение — нет. Кто контролирует формулировку — контролирует решение.',
        example: 'Говяжий фарш «80% мяса» продаётся лучше, чем «20% жира». Тот же продукт. Другой фрейм. Другие продажи.',
        tip: 'Переформулируй каждое важное решение в противоположном ключе перед тем, как решить. Если ответ меняется — решал фрейм, а не ты.',
      },
    },
  },
  {
    id: 'bandwagon-effect',
    order: 8,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Bandwagon Effect',
        hook: "You changed your mind because everyone else did.",
        body: "The more people believe something, the more you're inclined to believe it too — regardless of evidence. Popularity becomes proof. Consensus becomes truth. Your opinion is partly a headcount.",
        example: "Crypto surges because everyone is buying. You buy because everyone is buying. The price crashes. Everyone was just watching everyone else.",
        tip: "Ask: would I believe this if only three people agreed? If not, you're not reasoning — you're following.",
      },
      ru: {
        title: 'Эффект подножки',
        hook: 'Ты изменил мнение, потому что все остальные изменили.',
        body: 'Чем больше людей во что-то верят, тем сильнее ты склонен верить тоже — вне зависимости от доказательств. Популярность становится доказательством. Консенсус — истиной. Твоё мнение отчасти — это подсчёт голосов.',
        example: 'Криптовалюта растёт, потому что все покупают. Ты покупаешь, потому что все покупают. Цена рушится. Все просто смотрели друг на друга.',
        tip: 'Спроси: я бы верил в это, если бы согласились только трое? Если нет — ты не рассуждаешь, ты следуешь.',
      },
    },
  },
  {
    id: 'hindsight-bias',
    order: 9,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Hindsight Bias',
        hook: "After it happened, you were sure you knew it would.",
        body: "Once an event occurs, it feels inevitable in retrospect. You remember your prediction as more accurate than it was. This makes you overconfident about future predictions and blind to how uncertain the past actually was.",
        example: "After the financial crisis: 'Obviously the housing market was going to collapse.' Before: almost nobody said so publicly.",
        tip: "Keep a prediction log. Write down what you think will happen before it does. The gap between your forecast and your memory will surprise you.",
      },
      ru: {
        title: 'Предвзятость ретроспективы',
        hook: 'После того как всё случилось, ты был уверен, что знал заранее.',
        body: 'Когда событие произошло, оно кажется неизбежным задним числом. Ты помнишь свой прогноз точнее, чем он был. Это делает тебя самоуверенным в будущих прогнозах и слепым к тому, насколько неопределённым было прошлое.',
        example: 'После финансового кризиса: «Очевидно же, что рынок недвижимости должен был рухнуть.» До кризиса: почти никто этого публично не говорил.',
        tip: 'Веди журнал прогнозов. Записывай, что, по-твоему, произойдёт — до того как произойдёт. Разрыв между прогнозом и памятью тебя удивит.',
      },
    },
  },
  {
    id: 'halo-effect',
    order: 10,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Halo Effect',
        hook: "You think they're smart because they're attractive.",
        body: "One positive trait — looks, charisma, status — bleeds into your assessment of everything else about a person. You assume competence from confidence, intelligence from appearance, honesty from charm. The halo makes you stop looking.",
        example: "Attractive defendants receive lighter sentences on average. Juries aren't corrupt — they're human. The halo does the judging.",
        tip: "Evaluate traits independently. Being good at one thing is not evidence of being good at anything else.",
      },
      ru: {
        title: 'Эффект ореола',
        hook: 'Ты думаешь, что он умный, потому что он привлекательный.',
        body: 'Одно положительное качество — внешность, харизма, статус — распространяется на всё остальное, что ты думаешь о человеке. Ты принимаешь уверенность за компетентность, внешность — за интеллект, обаяние — за честность. Ореол заставляет тебя прекратить смотреть.',
        example: 'Привлекательные подсудимые в среднем получают более мягкие приговоры. Присяжные не коррумпированы — они люди. Ореол судит вместо них.',
        tip: 'Оценивай качества независимо друг от друга. Быть хорошим в одном — не доказательство хороших качеств в другом.',
      },
    },
  },
  {
    id: 'status-quo-bias',
    order: 11,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Status Quo Bias',
        hook: "You're not choosing to stay. You're avoiding the effort of leaving.",
        body: "The current state feels like the default. Any change requires justification; staying doesn't. So you stay — in jobs, relationships, habits, subscriptions — not because they're good, but because leaving takes effort and the status quo takes none.",
        example: "Most people never change their default settings. Apps, insurance plans, pension funds — defaults win not by merit but by inertia.",
        tip: "Periodically ask: if I were choosing this from scratch today, would I? If the honest answer is no — you're not choosing. You're drifting.",
      },
      ru: {
        title: 'Предвзятость статус-кво',
        hook: 'Ты не выбираешь остаться. Ты избегаешь усилий, чтобы уйти.',
        body: 'Текущее состояние воспринимается как данность. Любое изменение требует обоснования; оставаться — нет. Поэтому ты остаёшься — в работе, отношениях, привычках, подписках — не потому что хорошо, а потому что уходить требует усилий, а статус-кво — нет.',
        example: 'Большинство людей никогда не меняют настройки по умолчанию. Приложения, страховки, пенсионные фонды — дефолты побеждают не достоинствами, а инерцией.',
        tip: 'Периодически спрашивай: если бы я выбирал это с нуля сегодня — выбрал бы? Если честный ответ — нет, ты не выбираешь. Ты дрейфуешь.',
      },
    },
  },
  {
    id: 'fundamental-attribution-error',
    order: 12,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Fundamental Attribution Error',
        hook: "When they fail, it's their fault. When you fail, it's the circumstances.",
        body: "You judge other people's behavior by their character and ignore the situation they're in. You judge your own behavior by the situation and downplay your character. The same action means something different depending on who performed it.",
        example: "Someone cuts you off in traffic: 'What an aggressive driver.' You cut someone off: 'I was running late and the lane was confusing.'",
        tip: "Before judging someone's behavior, ask what situational pressures they might be under. Apply the same generosity you give yourself.",
      },
      ru: {
        title: 'Фундаментальная ошибка атрибуции',
        hook: 'Когда они ошибаются — это их вина. Когда ты — обстоятельства.',
        body: 'Поведение других людей ты оцениваешь через их характер и игнорируешь ситуацию. Своё собственное поведение — через ситуацию и преуменьшаешь роль характера. Одно и то же действие означает разное в зависимости от того, кто его совершил.',
        example: 'Кто-то подрезает тебя на дороге: «Какой агрессивный водитель». Ты подрезаешь кого-то: «Опаздывал, разметка была непонятная».',
        tip: 'Перед тем как судить о чьём-то поведении, спроси: под каким ситуативным давлением они могут находиться? Прояви ту же щедрость, что и к себе.',
      },
    },
  },
  {
    id: 'planning-fallacy',
    order: 13,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Planning Fallacy',
        hook: "It'll take two weeks. It'll take three months.",
        body: "We consistently underestimate how long tasks will take, how much they'll cost, and how many things will go wrong — even when we have direct experience with similar projects going over time and budget. Optimism overrides memory.",
        example: "The Sydney Opera House was planned for 4 years and $7M. It took 14 years and $102M. Every major infrastructure project has a version of this story.",
        tip: "Use reference class forecasting: find similar past projects and use their actual completion times as your baseline — not your optimistic plan.",
      },
      ru: {
        title: 'Ошибка планирования',
        hook: 'Займёт две недели. Займёт три месяца.',
        body: 'Мы постоянно недооцениваем, сколько займут задачи, сколько будет стоить и сколько всего пойдёт не так — даже когда у нас есть прямой опыт с похожими проектами, которые выбивались из сроков и бюджета. Оптимизм перекрывает память.',
        example: 'Сиднейский оперный театр планировали построить за 4 года и $7 млн. Строили 14 лет и потратили $102 млн. У каждого крупного проекта есть своя версия этой истории.',
        tip: 'Используй прогнозирование по референс-классу: найди похожие прошлые проекты и используй их реальные сроки как отправную точку — а не свой оптимистичный план.',
      },
    },
  },
  {
    id: 'curse-of-knowledge',
    order: 14,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Curse of Knowledge',
        hook: "You can't remember what it was like not to know this.",
        body: "Once you know something, you can't imagine not knowing it. This makes you a bad teacher, a bad communicator, and a bad designer — because you consistently overestimate how much your audience already understands.",
        example: "In a study, people tapped out famous songs with their fingers. They estimated listeners would recognize 50% of songs. The actual rate was 2.5%. The tapper hears the full melody in their head. The listener hears random taps.",
        tip: "When explaining anything, assume your audience knows nothing. Then assume even less. You'll still probably overshoot.",
      },
      ru: {
        title: 'Проклятие знания',
        hook: 'Ты уже не можешь вспомнить, каково это — не знать этого.',
        body: 'Узнав что-то, ты не можешь представить, как это — не знать. Это делает тебя плохим учителем, плохим коммуникатором и плохим дизайнером — потому что ты постоянно переоцениваешь, сколько твоя аудитория уже понимает.',
        example: 'В одном исследовании люди отстукивали пальцами известные мелодии. Они считали, что слушатели узнают 50% песен. Реальный показатель — 2,5%. Тот, кто стучит, слышит в голове всю мелодию. Слушатель слышит случайные удары.',
        tip: 'Объясняя что-либо, предполагай, что аудитория не знает ничего. Потом предполагай ещё меньше. Ты всё равно, скорее всего, перестараешься.',
      },
    },
  },
  {
    id: 'gamblers-fallacy',
    order: 15,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: "Gambler's Fallacy",
        hook: "It's been tails five times. Heads is due.",
        body: "Random events don't have memory. A coin doesn't know it's been tails five times. Each flip is independent. But your brain detects patterns even where none exist — and expects the universe to 'balance out.'",
        example: "Roulette lands on red seven times in a row. Bets on black surge. The wheel doesn't know. The casino does.",
        tip: "In any independent random process, past outcomes tell you nothing about the next one. 'Due' is not a real concept in probability.",
      },
      ru: {
        title: 'Ошибка игрока',
        hook: 'Пять раз подряд решка. Орёл уже должен выпасть.',
        body: 'Случайные события не имеют памяти. Монета не знает, что пять раз была решка. Каждый бросок независим. Но мозг видит паттерны там, где их нет — и ожидает, что вселенная «уравновесится».',
        example: 'Рулетка семь раз подряд выдаёт красное. Ставки на чёрное резко растут. Колесо не знает. Казино знает.',
        tip: 'В любом независимом случайном процессе прошлые результаты ничего не говорят о следующем. «Пора» — не реальная концепция в теории вероятностей.',
      },
    },
  },
  {
    id: 'loss-aversion',
    order: 16,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Loss Aversion',
        hook: "Losing $100 hurts more than winning $100 feels good.",
        body: "Losses feel roughly twice as painful as equivalent gains feel pleasurable. This asymmetry warps every decision involving risk — making you hold losing investments, avoid beneficial risks, and stay in bad situations just to avoid locking in a loss.",
        example: "You hold a losing stock hoping it'll recover rather than selling and moving on. The rational move is clear. The emotional math doesn't add up that way.",
        tip: "When facing a decision, ask: am I making this choice based on what's best going forward, or to avoid the pain of admitting a loss?",
      },
      ru: {
        title: 'Неприятие потерь',
        hook: 'Потерять 100 долларов больнее, чем приятно их выиграть.',
        body: 'Потери ощущаются примерно вдвое болезненнее, чем равнозначные приобретения приятны. Эта асимметрия искажает каждое решение, связанное с риском — заставляя держать убыточные вложения, избегать полезных рисков и оставаться в плохих ситуациях только чтобы не фиксировать потерю.',
        example: 'Ты держишь убыточную акцию в надежде, что она восстановится, вместо того чтобы продать и двигаться дальше. Рациональный выбор очевиден. Эмоциональная математика так не считает.',
        tip: 'Принимая решение, спроси: я делаю этот выбор исходя из того, что лучше в будущем, или чтобы избежать боли от признания потери?',
      },
    },
  },
  {
    id: 'ikea-effect',
    order: 17,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'IKEA Effect',
        hook: "You love it because you built it. Not because it's good.",
        body: "When you put effort into creating something, you overvalue it — disproportionately to its actual quality. Labor creates love. The problem is, your attachment blinds you to its real flaws and makes you resistant to criticism.",
        example: "Founders can't kill features they built. Parents can't see their children's faults clearly. The work you did is now inseparable from the judgment you make about it.",
        tip: "Get an outsider's honest assessment before concluding your creation is exceptional. Effort invested is not evidence of quality produced.",
      },
      ru: {
        title: 'Эффект ИКЕА',
        hook: 'Тебе это нравится, потому что ты это сделал. Не потому что это хорошо.',
        body: 'Когда ты вкладываешь усилия в создание чего-либо, ты переоцениваешь это — непропорционально реальному качеству. Труд порождает привязанность. Проблема в том, что эта привязанность ослепляет тебя к реальным недостаткам и делает тебя устойчивым к критике.',
        example: 'Основатели не могут удалить функции, которые сами создали. Родители не видят недостатков своих детей объективно. Твоя работа неотделима от суждения, которое ты о ней выносишь.',
        tip: 'Получи честную оценку стороннего человека, прежде чем решить, что твоё творение исключительно. Вложенные усилия — не доказательство качества результата.',
      },
    },
  },
  {
    id: 'spotlight-effect',
    order: 18,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Spotlight Effect',
        hook: "Nobody noticed. You were the only one watching.",
        body: "You overestimate how much other people notice and remember about you — your mistakes, your appearance, your awkward moment. In reality, everyone is too busy monitoring their own spotlight to pay sustained attention to yours.",
        example: "You spill coffee on your shirt before a meeting. You're convinced everyone noticed. Three hours later, nobody mentions it. They were thinking about their own problems.",
        tip: "Other people are not your audience. They're the main character in their own story, dealing with their own spotlight.",
      },
      ru: {
        title: 'Эффект прожектора',
        hook: 'Никто не заметил. Ты единственный, кто смотрел.',
        body: 'Ты переоцениваешь, насколько другие замечают и помнят о тебе — твои ошибки, внешность, неловкий момент. На самом деле все слишком заняты наблюдением за собственным прожектором, чтобы устойчиво следить за твоим.',
        example: 'Ты проливаешь кофе на рубашку перед встречей. Уверен, что все заметили. Через три часа никто не упоминает. Они думали о своих проблемах.',
        tip: 'Другие люди — не твоя аудитория. Они главные герои в собственной истории, занятые своим прожектором.',
      },
    },
  },
  {
    id: 'false-consensus-effect',
    order: 19,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'False Consensus Effect',
        hook: "You think most people agree with you. They don't.",
        body: "You overestimate how common your opinions, values, and behaviors are. Because your social environment reflects back beliefs similar to your own, you mistake your bubble for the world. Your normal is not the baseline.",
        example: "People who don't recycle believe most people don't recycle. People who do recycle believe most people do. Both are wrong. Both feel certain.",
        tip: "Before assuming your view is the majority view, find actual data. Your social circle is not a representative sample of humanity.",
      },
      ru: {
        title: 'Эффект ложного консенсуса',
        hook: 'Ты думаешь, что большинство людей согласны с тобой. Это не так.',
        body: 'Ты переоцениваешь, насколько распространены твои мнения, ценности и поведение. Потому что твоё социальное окружение отражает похожие взгляды, ты принимаешь свой пузырь за весь мир. Твоя норма — не общая норма.',
        example: 'Люди, которые не сортируют мусор, считают, что большинство не сортирует. Те, кто сортирует — что большинство сортирует. Оба неправы. Оба уверены.',
        tip: 'Перед тем как считать свою точку зрения мнением большинства, найди реальные данные. Твой социальный круг — не репрезентативная выборка человечества.',
      },
    },
  },
  {
    id: 'recency-bias',
    order: 20,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Recency Bias',
        hook: "What just happened feels like what will always happen.",
        body: "Recent events are weighted too heavily in your predictions and judgments. A good year makes the future feel bright. A bad week makes everything feel hopeless. Your brain mistakes 'just happened' for 'most representative.'",
        example: "After a market crash, investors predict more crashes. After a bull run, they predict more gains. Both predictions are shaped by recency, not evidence.",
        tip: "Deliberately look at longer time horizons before forming judgments. Recent history is not a reliable predictor — it's just the loudest signal right now.",
      },
      ru: {
        title: 'Предвзятость к недавнему',
        hook: 'То, что только что случилось, кажется тем, что будет всегда.',
        body: 'Недавним событиям придаётся слишком большой вес в прогнозах и суждениях. Хороший год делает будущее светлым. Плохая неделя делает всё безнадёжным. Мозг путает «только что случилось» с «наиболее показательным».',
        example: 'После обвала рынка инвесторы прогнозируют новые обвалы. После роста — новый рост. Оба прогноза сформированы недавностью, а не доказательствами.',
        tip: 'Намеренно смотри на более длинные горизонты перед формированием суждений. Недавняя история — не надёжный предиктор. Это просто самый громкий сигнал прямо сейчас.',
      },
    },
  },
  {
    id: 'optimism-bias',
    order: 21,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Optimism Bias',
        hook: "You think bad things are more likely to happen to other people.",
        body: "Most people believe they're less likely than average to get divorced, have a car accident, develop cancer, or lose their job. Statistically, we can't all be below average. The bias is especially dangerous because it feels like confidence.",
        example: "80% of drivers consider themselves above average. Half of them are wrong. The same math applies to your business, your health, your relationships.",
        tip: "When making plans, actively force yourself to imagine failure scenarios. Not to be pessimistic — to be accurate.",
      },
      ru: {
        title: 'Оптимистическая предвзятость',
        hook: 'Ты думаешь, что плохие вещи чаще случаются с другими людьми.',
        body: 'Большинство людей считают, что они с меньшей вероятностью разведутся, попадут в ДТП, заболеют раком или потеряют работу — по сравнению со средним. Статистически мы не можем все быть ниже среднего. Предвзятость особенно опасна, потому что ощущается как уверенность.',
        example: '80% водителей считают себя выше среднего. Половина из них ошибается. Та же математика применима к твоему бизнесу, здоровью, отношениям.',
        tip: 'При составлении планов намеренно заставь себя представить сценарии провала. Не чтобы быть пессимистом — чтобы быть точным.',
      },
    },
  },
  {
    id: 'self-serving-bias',
    order: 22,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Self-Serving Bias',
        hook: "Your successes are your talent. Your failures are bad luck.",
        body: "You attribute positive outcomes to your own skill and effort, and negative outcomes to external factors. This protects your self-esteem but prevents you from learning accurately from failure — and makes you credit yourself with luck.",
        example: "Project succeeds: 'I worked hard and made smart decisions.' Project fails: 'The market timing was off and the team let me down.'",
        tip: "After a failure, write down three things you personally did that contributed to it before blaming anything external. The truth is usually shared.",
      },
      ru: {
        title: 'Самооправдательная предвзятость',
        hook: 'Твои успехи — это твой талант. Твои неудачи — невезение.',
        body: 'Положительные результаты ты объясняешь собственными умениями и усилиями, а отрицательные — внешними факторами. Это защищает самооценку, но мешает точно учиться на неудачах — и заставляет тебя присваивать себе заслуги удачи.',
        example: 'Проект успешен: «Я усердно работал и принимал умные решения». Проект провалился: «Время было неподходящим и команда подвела».',
        tip: 'После неудачи запиши три вещи, которые ты лично сделал и которые к ней привели — прежде чем винить что-то внешнее. Правда обычно распределена.',
      },
    },
  },
  {
    id: 'in-group-bias',
    order: 23,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'In-Group Bias',
        hook: "You're more forgiving of people who are like you.",
        body: "You favor members of your own group — your nationality, profession, sports team, political tribe — and judge them by different standards than outsiders. The same behavior looks reasonable from your group and suspicious from theirs.",
        example: "Politicians from your party 'made a difficult call.' Politicians from the other party 'acted in bad faith.' The action was identical.",
        tip: "Before judging someone's behavior, swap the group label and ask if you'd feel the same way. If not, you're applying a double standard.",
      },
      ru: {
        title: 'Предвзятость своей группы',
        hook: 'Ты более снисходителен к людям, которые похожи на тебя.',
        body: 'Ты отдаёшь предпочтение членам своей группы — своей национальности, профессии, спортивной команде, политическому лагерю — и судишь их по другим стандартам, чем посторонних. Одно и то же поведение выглядит разумным от своей группы и подозрительным от чужой.',
        example: 'Политики из твоей партии «приняли трудное решение». Политики из другой «действовали недобросовестно». Действие было идентичным.',
        tip: 'Прежде чем осуждать чьё-то поведение, поменяй групповой ярлык и спроси, чувствовал бы ты то же самое. Если нет — ты применяешь двойной стандарт.',
      },
    },
  },
  {
    id: 'normalcy-bias',
    order: 24,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Normalcy Bias',
        hook: "Something is clearly wrong. You're waiting to see if it gets worse.",
        body: "When faced with a potential disaster, your brain defaults to assuming things will continue as normal. You underestimate both the probability of a crisis and the severity of its impact — and delay action until the evidence is undeniable. By then, it's often too late.",
        example: "People in burning buildings spend precious minutes gathering belongings instead of evacuating. Normalcy bias tells them it probably isn't that serious.",
        tip: "When warning signs appear, act on limited information. The cost of a false alarm is almost always lower than the cost of acting too late.",
      },
      ru: {
        title: 'Предвзятость нормальности',
        hook: 'Что-то явно идёт не так. Ты ждёшь, станет ли хуже.',
        body: 'Столкнувшись с потенциальной катастрофой, мозг по умолчанию предполагает, что всё продолжится как обычно. Ты недооцениваешь и вероятность кризиса, и серьёзность его последствий — и откладываешь действия до тех пор, пока доказательства не станут неопровержимыми. К тому времени часто уже слишком поздно.',
        example: 'Люди в горящих зданиях тратят драгоценные минуты на сбор вещей вместо эвакуации. Предвзятость нормальности говорит им, что всё, наверное, не так серьёзно.',
        tip: 'Когда появляются тревожные признаки, действуй при ограниченной информации. Цена ложной тревоги почти всегда ниже цены слишком позднего действия.',
      },
    },
  },
  {
    id: 'zero-risk-bias',
    order: 25,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Zero-Risk Bias',
        hook: "You'd rather eliminate a small risk completely than reduce a bigger one significantly.",
        body: "Eliminating a risk entirely feels psychologically satisfying in a way that reducing a risk doesn't — even if the reduction saves more lives, money, or harm. Zero has emotional appeal beyond its mathematical value.",
        example: "People prefer a policy that eliminates 1 death from cause A over one that prevents 10 deaths from cause B. Zero deaths from A feels like a win. Ten fewer deaths from B feels abstract.",
        tip: "When evaluating risk-reduction options, focus on expected value — total risk reduced — not on which option sounds more complete.",
      },
      ru: {
        title: 'Предвзятость нулевого риска',
        hook: 'Ты предпочтёшь полностью устранить маленький риск, чем значительно снизить большой.',
        body: 'Полное устранение риска ощущается психологически удовлетворяющим так, как снижение риска — нет. Даже если снижение сохраняет больше жизней, денег или предотвращает больший вред. Ноль имеет эмоциональную привлекательность, выходящую за рамки математической ценности.',
        example: 'Люди предпочитают политику, которая устраняет 1 смерть от причины A, той, что предотвращает 10 смертей от причины B. Ноль смертей от A ощущается как победа. Десять меньше от B — абстракция.',
        tip: 'При оценке вариантов снижения риска фокусируйся на ожидаемой ценности — общем сниженном риске — а не на том, какой вариант звучит более полным.',
      },
    },
  },
  {
    id: 'hyperbolic-discounting',
    order: 26,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Hyperbolic Discounting',
        hook: "$100 now beats $150 in a month. Every time.",
        body: "You overvalue immediate rewards relative to future ones — and the degree of overvaluation is irrational and inconsistent. You'll wait a year for a 10% bonus, but not a week for the same 10%. The closer the reward, the more distorted your judgment becomes.",
        example: "You'll start the diet on Monday. Every Sunday night for six months. The future self who benefits always seems capable of handling the sacrifice. The present self wants the cake.",
        tip: "When making decisions with future consequences, ask what your future self will think of this choice. Then weight that answer more than your current preference.",
      },
      ru: {
        title: 'Гиперболическое дисконтирование',
        hook: '100 долларов сейчас лучше, чем 150 через месяц. Всегда.',
        body: 'Ты переоцениваешь немедленные вознаграждения относительно будущих — и степень переоценки иррациональна и непоследовательна. Ты подождёшь год ради 10% бонуса, но не неделю ради того же 10%. Чем ближе награда — тем сильнее искажается суждение.',
        example: 'Ты начнёшь диету в понедельник. Каждое воскресенье вечером на протяжении шести месяцев. Будущее «я», которое получит выгоду, всегда кажется способным на жертву. Нынешнее «я» хочет торт.',
        tip: 'Принимая решения с будущими последствиями, спроси, что твоё будущее «я» подумает об этом выборе. Затем взвесь этот ответ больше, чем текущее предпочтение.',
      },
    },
  },
  {
    id: 'bystander-effect',
    order: 27,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Bystander Effect',
        hook: "You didn't help because you assumed someone else would.",
        body: "The more people present in an emergency, the less likely any individual is to help. Responsibility diffuses across the crowd. Everyone assumes someone else is more qualified, more aware, or more responsible. Nobody acts.",
        example: "Kitty Genovese was attacked in New York with 38 witnesses. Almost no one called the police. Each assumed others had already done so.",
        tip: "In emergencies, don't wait for consensus. Point at one specific person and say 'you — call an ambulance.' Diffused responsibility only dissolves when it becomes personal.",
      },
      ru: {
        title: 'Эффект свидетеля',
        hook: 'Ты не помог, потому что думал, что кто-нибудь другой поможет.',
        body: 'Чем больше людей присутствует при чрезвычайной ситуации, тем меньше вероятность, что кто-то из них поможет. Ответственность рассредоточивается по толпе. Каждый предполагает, что кто-то другой более квалифицирован, более осведомлён или более ответственен. Никто не действует.',
        example: 'На Китти Дженовезе напали в Нью-Йорке при 38 свидетелях. Почти никто не вызвал полицию. Каждый думал, что другие уже это сделали.',
        tip: 'В чрезвычайных ситуациях не жди консенсуса. Укажи на конкретного человека и скажи: «Ты — вызови скорую». Размытая ответственность растворяется только тогда, когда становится личной.',
      },
    },
  },
  {
    id: 'frequency-illusion',
    order: 28,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Frequency Illusion',
        hook: "You just learned a new word. Now it's everywhere.",
        body: "Once you notice something — a car model, a concept, a name — your brain starts flagging every occurrence. It feels like the thing suddenly appeared everywhere. It didn't. You just started seeing it. The world didn't change. Your filter did.",
        example: "You get pregnant and suddenly every third person you see is also pregnant. The rate hasn't changed. Your attention has been recalibrated.",
        tip: "When something seems to be 'appearing everywhere,' ask: was I just not noticing before? Frequency illusion is a cue that you've updated your filter — not that the world changed.",
      },
      ru: {
        title: 'Иллюзия частоты',
        hook: 'Ты только что узнал новое слово. Теперь оно везде.',
        body: 'Как только ты замечаешь что-то — модель машины, концепцию, имя — мозг начинает отмечать каждое упоминание. Кажется, что это вдруг появилось повсюду. Нет. Ты просто начал это видеть. Мир не изменился. Изменился твой фильтр.',
        example: 'Ты узнаёшь о беременности и внезапно каждая третья встречная тоже беременна. Частота не изменилась. Твоё внимание перекалибровалось.',
        tip: 'Когда что-то кажется «везде» — спроси себя: я просто не замечал раньше? Иллюзия частоты — сигнал, что ты обновил фильтр, а не что мир изменился.',
      },
    },
  },
  {
    id: 'negativity-bias',
    order: 29,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Negativity Bias',
        hook: "One bad review cancels ten good ones. In your mind, at least.",
        body: "Negative experiences hit harder and stick longer than positive ones of the same intensity. Your brain processes bad news faster, remembers it more vividly, and weighs it more heavily. This kept your ancestors alive. It keeps you stuck.",
        example: "A performance review with nine compliments and one criticism. You go home thinking about the criticism. Your brain filed the compliments as background noise.",
        tip: "Actively log positive events — they won't stick naturally. At the end of each day, name three things that went well. You're not being naive. You're correcting a calibration error.",
      },
      ru: {
        title: 'Предвзятость к негативу',
        hook: 'Один плохой отзыв перечёркивает десять хороших. По крайней мере, в твоей голове.',
        body: 'Негативный опыт бьёт сильнее и остаётся дольше, чем позитивный той же интенсивности. Мозг обрабатывает плохие новости быстрее, помнит их ярче и взвешивает тяжелее. Это сохранило жизнь твоим предкам. Оно держит тебя в ловушке.',
        example: 'Оценка работы с девятью комплиментами и одной критикой. Ты уходишь домой, думая о критике. Мозг зарегистрировал комплименты как фоновый шум.',
        tip: 'Активно фиксируй позитивные события — сами по себе они не задержатся. В конце каждого дня назови три вещи, которые прошли хорошо. Это не наивность. Это коррекция ошибки калибровки.',
      },
    },
  },
  {
    id: 'choice-overload',
    order: 30,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Choice Overload',
        hook: "More options. Less satisfaction. Every time.",
        body: "When faced with too many choices, people make worse decisions, feel less satisfied with what they chose, and are more likely to choose nothing at all. Freedom to choose feels like it should produce better outcomes. Often it produces paralysis and regret.",
        example: "A jam study: 24 varieties attract more browsers, but 6 varieties generate 10x more purchases. More options made buying feel harder and less certain.",
        tip: "Limit your own options before deciding. Eliminate obviously bad choices early. Satisficing — choosing 'good enough' — often leads to more satisfaction than finding the 'best.'",
      },
      ru: {
        title: 'Перегрузка выбором',
        hook: 'Больше вариантов. Меньше удовлетворения. Всегда.',
        body: 'Столкнувшись со слишком большим выбором, люди принимают худшие решения, меньше довольны тем, что выбрали, и с большей вероятностью не выберут ничего. Свобода выбора должна давать лучшие результаты. Часто она производит паралич и сожаление.',
        example: 'Исследование с джемом: 24 сорта привлекают больше покупателей, но 6 сортов дают в 10 раз больше покупок. Больший выбор затруднял решение.',
        tip: 'Ограничивай варианты перед решением. Рано исключай явно плохие варианты. «Достаточно хорошее» часто приносит больше удовлетворения, чем поиск «лучшего».',
      },
    },
  },
  {
    id: 'authority-bias',
    order: 31,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Authority Bias',
        hook: "He's wearing a white coat. He must be right.",
        body: "You assign greater credibility to the opinions of authority figures — regardless of whether that authority is relevant to the question at hand. Titles, uniforms, and confident delivery override your own judgment. You don't question it. You defer.",
        example: "In Milgram's experiments, 65% of participants administered what they believed were dangerous electric shocks — simply because someone in a lab coat told them to.",
        tip: "Separate the person from the claim. Ask: is this person's authority actually relevant here? A doctor is an authority on medicine, not necessarily on business, relationships, or politics.",
      },
      ru: {
        title: 'Предвзятость авторитета',
        hook: 'На нём белый халат. Значит, он прав.',
        body: 'Ты приписываешь большую достоверность мнениям авторитетных фигур — независимо от того, относится ли их авторитет к рассматриваемому вопросу. Титулы, форма и уверенная подача перекрывают твоё собственное суждение. Ты не ставишь под сомнение. Ты подчиняешься.',
        example: 'В экспериментах Милгрэма 65% участников наносили то, что считали опасными ударами током — просто потому что человек в белом халате им так сказал.',
        tip: 'Отделяй человека от утверждения. Спроси: авторитет этого человека действительно релевантен здесь? Врач — авторитет в медицине, не обязательно в бизнесе или отношениях.',
      },
    },
  },
  {
    id: 'scarcity-illusion',
    order: 32,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Scarcity Illusion',
        hook: "'Only 3 left in stock.' You want it more now.",
        body: "Things become more desirable when they appear scarce — even if the scarcity is artificial, the quality is unchanged, and you didn't want it before. Your brain interprets scarcity as a signal of value. Marketers have known this for decades.",
        example: "'Limited edition.' 'Offer ends tonight.' 'Only 2 seats at this price.' None of these change what you're buying. All of them change what you're willing to pay.",
        tip: "When scarcity creates urgency, pause and ask: would I want this if there were 1000 in stock? If the answer is no — the scarcity was doing the selling, not the product.",
      },
      ru: {
        title: 'Иллюзия дефицита',
        hook: '«Осталось только 3 штуки». Теперь ты хочешь это сильнее.',
        body: 'Вещи становятся более желанными, когда кажутся дефицитными — даже если дефицит искусственный, качество не изменилось, и раньше ты этого не хотел. Мозг интерпретирует дефицит как сигнал ценности. Маркетологи знают это десятилетиями.',
        example: '«Лимитированная серия». «Предложение заканчивается сегодня ночью». «Только 2 места по этой цене». Ничто из этого не меняет то, что ты покупаешь. Всё это меняет то, сколько ты готов заплатить.',
        tip: 'Когда дефицит создаёт срочность, остановись и спроси: хотел бы я это, если бы было 1000 штук? Если нет — продавал дефицит, а не продукт.',
      },
    },
  },
  {
    id: 'hot-hand-fallacy',
    order: 33,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Hot Hand Fallacy',
        hook: "She scored three times in a row. She's on fire. Back her.",
        body: "You believe that a person who has experienced recent success has a higher probability of future success. In most cases, the belief is false — each event is independent. Past performance in random or complex systems doesn't make the next event more likely.",
        example: "Basketball fans and coaches believe players are 'hot' and should shoot more. Statistical analysis shows almost no evidence that recent shots predict future shots.",
        tip: "Ask whether the domain is skill-based or random. In skill domains, streaks can reflect real ability. In random domains — coins, markets, dice — the hot hand doesn't exist.",
      },
      ru: {
        title: 'Иллюзия «горячей руки»',
        hook: 'Она забила три раза подряд. Она в ударе. Ставь на неё.',
        body: 'Ты веришь, что человек, недавно успешный, имеет более высокую вероятность будущего успеха. В большинстве случаев это неверно — каждое событие независимо. Прошлые результаты в случайных системах не делают следующее событие более вероятным.',
        example: 'Болельщики и тренеры баскетбола верят, что игроки бывают «в ударе» и должны бросать чаще. Статистический анализ почти не находит доказательств, что недавние броски предсказывают будущие.',
        tip: 'Спроси, основана ли область на навыке или случайности. В навыковых областях серии могут отражать реальные способности. В случайных — монеты, рынки, кости — «горячей руки» не существует.',
      },
    },
  },
  {
    id: 'peak-end-rule',
    order: 34,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Peak-End Rule',
        hook: "You don't remember the whole experience. You remember how it peaked and how it ended.",
        body: "Your memory of an experience is determined almost entirely by its most intense moment and its final moments — not by the average or total. A long painful experience that ends gently feels better than a short one that ends badly.",
        example: "Patients rating colonoscopies: those whose procedure ended gradually (less pain at the end) rated the whole experience as less unpleasant — even when the total duration of discomfort was longer.",
        tip: "Design experiences to end well. A bad meeting that closes with a clear win is remembered better than an average meeting that trails off. Pay attention to endings.",
      },
      ru: {
        title: 'Правило пика и конца',
        hook: 'Ты помнишь не весь опыт. Ты помнишь пик и конец.',
        body: 'Твоя память о пережитом определяется почти полностью самым интенсивным моментом и финальными моментами — не средним и не общим. Долгий болезненный опыт, заканчивающийся мягко, ощущается лучше, чем короткий, заканчивающийся плохо.',
        example: 'Пациенты, оценивающие колоноскопию: те, чья процедура завершалась плавно (меньше боли в конце), оценивали весь опыт менее неприятным — даже когда общая продолжительность дискомфорта была дольше.',
        tip: 'Проектируй опыт так, чтобы он заканчивался хорошо. Плохое совещание, завершившееся явной победой, помнится лучше, чем среднее, постепенно сошедшее на нет.',
      },
    },
  },
  {
    id: 'mental-accounting',
    order: 35,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Mental Accounting',
        hook: "Found money feels different from earned money. It isn't.",
        body: "You treat money differently depending on where it came from or what it's 'meant for.' A tax refund gets spent freely; a salary is budgeted carefully. A gambling win goes back to gambling. Money is fungible — a dollar is a dollar — but your brain assigns it emotional categories.",
        example: "People spend more with credit cards than cash. The physical act of handing over cash triggers loss aversion. The card doesn't. Same money. Different mental account.",
        tip: "When spending 'found' money, bonus money, or gift money — apply the same scrutiny you'd give to earned money. The source doesn't change the value.",
      },
      ru: {
        title: 'Ментальный учёт',
        hook: 'Найденные деньги ощущаются иначе, чем заработанные. Это не так.',
        body: 'Ты обращаешься с деньгами по-разному в зависимости от того, откуда они пришли или для чего «предназначены». Налоговый возврат тратится свободно; зарплата расходуется аккуратно. Деньги — взаимозаменяемые: доллар есть доллар — но мозг присваивает им эмоциональные категории.',
        example: 'Люди тратят больше по кредитным картам, чем наличными. Физический акт передачи наличных вызывает неприятие потерь. Карта — нет. Те же деньги. Разные ментальные счета.',
        tip: 'Когда тратишь «найденные» деньги, бонусы или подарки — применяй тот же контроль, что к заработанным. Источник не меняет ценность.',
      },
    },
  },
  {
    id: 'decoy-effect',
    order: 36,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Decoy Effect',
        hook: "The third option was only added to make you choose the second one.",
        body: "Adding an asymmetrically dominated option — a decoy — shifts preferences between two other options. You weren't choosing between A and B. You were being steered. The decoy exists for no purpose except to change your choice.",
        example: "Small popcorn: $3. Large: $7. Medium: $6.50. The medium is a decoy — it makes the large look like good value. Without it, far fewer people choose the large.",
        tip: "When a 'middle' option appears, ask whether it was constructed to make another option look better. Remove it mentally and see if your preference changes.",
      },
      ru: {
        title: 'Эффект приманки',
        hook: 'Третий вариант добавили только затем, чтобы ты выбрал второй.',
        body: 'Добавление асимметрично доминируемого варианта — приманки — смещает предпочтения между двумя другими. Ты не выбирал между A и B. Тебя направляли. Приманка существует только для того, чтобы изменить твой выбор.',
        example: 'Маленький попкорн: 200 руб. Большой: 500 руб. Средний: 470 руб. Средний — приманка: он делает большой похожим на выгодную покупку. Без него гораздо меньше людей берут большой.',
        tip: 'Когда появляется «средний» вариант, спроси: его создали, чтобы другой выглядел лучше? Убери его мысленно и посмотри, изменится ли твоё предпочтение.',
      },
    },
  },
  {
    id: 'action-bias',
    order: 37,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Action Bias',
        hook: "Something went wrong. You feel like you need to do something. Anything.",
        body: "When faced with uncertainty or a problem, you feel compelled to act — even when inaction would produce better results. Doing something feels like competence. Doing nothing feels like failure. The pressure to act can be worse than the problem you're trying to fix.",
        example: "Soccer goalkeepers facing penalty kicks: they jump left or right almost every time. Staying in the center is statistically the best choice — but it feels passive. So they jump.",
        tip: "Before acting in a crisis, ask: is this action actually likely to improve things, or am I acting to feel less helpless? Sometimes the best action is deliberate inaction.",
      },
      ru: {
        title: 'Предвзятость к действию',
        hook: 'Что-то пошло не так. Ты чувствуешь, что нужно что-то сделать. Хоть что-нибудь.',
        body: 'Столкнувшись с неопределённостью или проблемой, ты чувствуешь принуждение действовать — даже когда бездействие дало бы лучшие результаты. Что-то делать ощущается как компетентность. Ничего не делать — как провал. Давление действовать может быть хуже проблемы, которую ты пытаешься исправить.',
        example: 'Вратари, принимающие пенальти: они прыгают влево или вправо почти всегда. Оставаться в центре — статистически лучший выбор, но это ощущается как пассивность. Поэтому они прыгают.',
        tip: 'Перед тем как действовать в кризисе, спроси: это действие действительно улучшит ситуацию, или я действую, чтобы чувствовать себя менее беспомощным? Иногда лучшее действие — намеренное бездействие.',
      },
    },
  },
  {
    id: 'clustering-illusion',
    order: 38,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Clustering Illusion',
        hook: "You see a pattern. There isn't one.",
        body: "Humans are pattern-recognition machines — and we're so good at it that we find patterns in pure noise. Random sequences look non-random to us. Clusters appear meaningful. We build narratives around statistical accidents and mistake noise for signal.",
        example: "WWII London bombing: civilians mapped the bomb strikes and saw clusters — evidence of deliberate targeting. Statistical analysis showed the distribution was perfectly random.",
        tip: "When you spot a pattern in a small dataset, ask: could this be random? Randomness produces clusters naturally. Your job is to demand enough data before concluding the pattern is real.",
      },
      ru: {
        title: 'Иллюзия кластеров',
        hook: 'Ты видишь паттерн. Его нет.',
        body: 'Люди — машины распознавания паттернов. И мы настолько хороши в этом, что находим паттерны в чистом шуме. Случайные последовательности кажутся нам неслучайными. Кластеры выглядят значимыми. Мы строим нарративы вокруг статистических случайностей.',
        example: 'Бомбардировки Лондона во Второй мировой: жители нанесли удары на карту и увидели кластеры — доказательства целенаправленных атак. Статистический анализ показал, что распределение было совершенно случайным.',
        tip: 'Заметив паттерн в небольшой выборке, спроси: может ли это быть случайным? Случайность естественно порождает кластеры. Твоя задача — требовать достаточно данных, прежде чем признавать паттерн реальным.',
      },
    },
  },
  {
    id: 'belief-perseverance',
    order: 39,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Belief Perseverance',
        hook: "You've been shown the evidence is wrong. You still believe it.",
        body: "Once a belief is formed, people maintain it even after the information that originally caused it has been thoroughly discredited. The belief takes on a life of its own — supported by new rationalizations rather than the original (false) evidence.",
        example: "In a study, participants were shown false information. Then researchers clearly debunked it. Participants still held the belief — and had generated new reasons to support it that were entirely their own.",
        tip: "When foundational evidence for a belief is challenged, ask: if I'd never believed this, would I believe it now? If not, the belief is persevering without justification.",
      },
      ru: {
        title: 'Устойчивость убеждений',
        hook: 'Тебе показали, что доказательства неверны. Ты всё равно веришь.',
        body: 'Однажды сформированное убеждение люди сохраняют даже после того, как информация, первоначально вызвавшая его, была полностью опровергнута. Убеждение живёт своей жизнью — поддерживаемое новыми рационализациями, а не исходными (ложными) доказательствами.',
        example: 'В исследовании участникам показывали ложную информацию. Затем её чётко опровергали. Участники всё равно придерживались убеждения — и сгенерировали новые причины его поддержать, уже полностью своими.',
        tip: 'Когда базовые доказательства убеждения оспариваются, спроси: если бы я никогда не верил в это — поверил бы я сейчас? Если нет, убеждение сохраняется без оснований.',
      },
    },
  },
  {
    id: 'ostrich-effect',
    order: 40,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Ostrich Effect',
        hook: "You haven't checked your bank account in two weeks.",
        body: "People avoid information that might be negative or anxiety-inducing — even when that information would help them make better decisions. Ignoring bad news doesn't make it go away. It just means you're uninformed when it arrives.",
        example: "Investors check their portfolios less often during market downturns. The portfolio doesn't improve from not being looked at. But the pain of checking feels worse than the pain of not knowing.",
        tip: "Schedule regular reviews of things you avoid. Your bank account, your health metrics, your project status. The anxiety of knowing is almost always lower than the accumulated anxiety of not knowing.",
      },
      ru: {
        title: 'Эффект страуса',
        hook: 'Ты не проверял банковский счёт две недели.',
        body: 'Люди избегают информации, которая может оказаться негативной или вызывающей тревогу — даже когда эта информация помогла бы принять лучшие решения. Игнорирование плохих новостей не заставляет их исчезнуть. Это просто значит, что ты не информирован, когда они настигнут тебя.',
        example: 'Инвесторы реже проверяют портфели во время падения рынков. Портфель не улучшается от того, что на него не смотрят. Но боль от проверки ощущается сильнее, чем боль незнания.',
        tip: 'Запланируй регулярные проверки того, чего избегаешь: банковский счёт, показатели здоровья, статус проекта. Тревога от знания почти всегда меньше, чем накопленная тревога от незнания.',
      },
    },
  },
  {
    id: 'texas-sharpshooter',
    order: 41,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Texas Sharpshooter Fallacy',
        hook: "You shot at the barn. Then you drew the target around the bullet holes.",
        body: "You cherry-pick data that clusters together, then invent a meaningful explanation for the cluster after the fact. The target is drawn after the shots, not before. The pattern was found, not predicted — but it feels like evidence.",
        example: "A town has an unusually high cancer rate. Residents point to a nearby factory. But if you check 1,000 towns, some will have high cancer rates by pure chance. The target gets drawn around those towns.",
        tip: "Ask whether a hypothesis was formed before or after looking at the data. If the data came first, the pattern might be a coincidence wearing the costume of causation.",
      },
      ru: {
        title: 'Ошибка техасского стрелка',
        hook: 'Ты стрелял по сараю. Потом нарисовал мишень вокруг пробоин.',
        body: 'Ты выбираешь данные, которые группируются вместе, затем постфактум придумываешь значимое объяснение кластеру. Мишень рисуется после выстрелов, а не до. Паттерн был найден, а не предсказан — но ощущается как доказательство.',
        example: 'В городе необычно высокий уровень онкологии. Жители указывают на ближайший завод. Но если проверить 1000 городов, некоторые будут иметь высокий уровень рака просто случайно. Мишень рисуется вокруг этих городов.',
        tip: 'Спроси, была ли гипотеза сформирована до или после изучения данных. Если данные были первыми, паттерн может быть совпадением в костюме причинно-следственной связи.',
      },
    },
  },
  {
    id: 'rosy-retrospection',
    order: 42,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Rosy Retrospection',
        hook: "It wasn't that good. But in memory, it was perfect.",
        body: "You remember past events more positively than they actually were. Vacations, relationships, jobs from the past all seem better in hindsight. The negative details fade. The inconveniences are forgotten. The past becomes a golden age that probably never existed.",
        example: "'School days were the best days of my life.' People say this despite remembering stress, social anxiety, and boredom. The selective editing happens automatically.",
        tip: "When nostalgia pulls you toward the past, write down the actual negatives from that period. Memory is an editor. It cuts the bad scenes before you can remember them.",
      },
      ru: {
        title: 'Розовая ретроспекция',
        hook: 'Это было не так хорошо. Но в памяти — идеально.',
        body: 'Ты помнишь прошлые события более позитивно, чем они были на самом деле. Отпуска, отношения, прошлая работа — всё кажется лучше в ретроспективе. Негативные детали стираются. Неудобства забываются. Прошлое становится золотым веком, которого, вероятно, никогда не было.',
        example: '«Школьные годы были лучшими в жизни». Люди говорят это, несмотря на то что помнят стресс, социальную тревогу и скуку. Выборочное редактирование происходит автоматически.',
        tip: 'Когда ностальгия тянет тебя в прошлое, запиши реальные негативные стороны того периода. Память — редактор. Она вырезает плохие сцены прежде, чем ты успеваешь их вспомнить.',
      },
    },
  },
  {
    id: 'overconfidence-effect',
    order: 43,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Overconfidence Effect',
        hook: "You're more confident in your answers than you have any right to be.",
        body: "People consistently overestimate the accuracy of their own knowledge and predictions. When people say they're 99% sure of something, they're right only about 80% of the time. Confidence and accuracy are poorly correlated — especially in experts.",
        example: "Doctors, lawyers, and engineers who rate themselves in the top 25% of their field: typically 70-80% of them claim this. The math doesn't work.",
        tip: "Assign explicit probability estimates to your beliefs and track them over time. You'll quickly discover your 'certain' opinions were far less reliable than they felt.",
      },
      ru: {
        title: 'Эффект самоуверенности',
        hook: 'Ты более уверен в своих ответах, чем у тебя есть право быть.',
        body: 'Люди систематически переоценивают точность своих знаний и прогнозов. Когда говорят, что на 99% уверены, они правы лишь около 80% времени. Уверенность и точность плохо коррелируют — особенно у экспертов.',
        example: 'Врачи, юристы и инженеры, считающие себя в топ-25% своей области: обычно 70-80% из них претендуют на это. Математика не сходится.',
        tip: 'Присваивай явные вероятностные оценки своим убеждениям и отслеживай их со временем. Ты быстро обнаружишь, что твои «несомненные» мнения были значительно менее надёжными, чем казалось.',
      },
    },
  },
  {
    id: 'stereotyping-bias',
    order: 44,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Stereotyping',
        hook: "You made a judgment before you had enough information. You filled in the rest.",
        body: "Stereotyping is a cognitive shortcut — applying group-level generalizations to individuals. It saves processing time. It's often wrong. The problem isn't that you use categories (everyone does), it's that you stop updating when individual evidence contradicts the category.",
        example: "You meet an engineer and assume they're introverted and bad at communication. They may be. Or they may be the most socially skilled person in the room. Your assumption prevented you from finding out.",
        tip: "Treat first impressions as provisional hypotheses, not conclusions. The person in front of you is always a sample size of one — update on them, not on their group.",
      },
      ru: {
        title: 'Стереотипизация',
        hook: 'Ты вынес суждение до того, как у тебя было достаточно информации. Остальное додумал.',
        body: 'Стереотипизация — когнитивный ярлык: применение групповых обобщений к индивидам. Это экономит время обработки. Это часто ошибочно. Проблема не в том, что ты используешь категории — все так делают. Проблема в том, что ты перестаёшь обновлять, когда индивидуальные доказательства противоречат категории.',
        example: 'Ты встречаешь инженера и предполагаешь, что он интроверт и плохо общается. Возможно. Или он может оказаться самым социально умелым человеком в комнате. Твоё предположение помешало тебе это узнать.',
        tip: 'Относись к первым впечатлениям как к предварительным гипотезам, а не выводам. Человек перед тобой — всегда выборка из одного. Обновляй оценку по нему, а не по его группе.',
      },
    },
  },
  {
    id: 'omission-bias',
    order: 45,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Omission Bias',
        hook: "Letting it happen feels less wrong than making it happen.",
        body: "People judge harmful actions more harshly than equally harmful inactions. Doing harm is worse than allowing harm — even when the outcome is identical. This asymmetry shapes medical decisions, policy, and everyday moral judgments in ways that aren't actually rational.",
        example: "Not vaccinating a child feels safer than vaccinating — even when the vaccine risk is far lower than the disease risk. The action of vaccinating feels more responsible for any outcome than the inaction of not vaccinating.",
        tip: "When evaluating options, treat omissions as choices. 'Doing nothing' is a decision with consequences, not a neutral baseline. Hold inaction to the same standard as action.",
      },
      ru: {
        title: 'Предвзятость бездействия',
        hook: 'Позволить случиться кажется менее плохим, чем сделать самому.',
        body: 'Люди судят о вредных действиях строже, чем о равно вредных бездействиях. Причинить вред хуже, чем допустить вред — даже когда исход идентичен. Эта асимметрия формирует медицинские решения, политику и повседневные моральные суждения способами, которые не являются рациональными.',
        example: 'Не прививать ребёнка кажется безопаснее, чем прививать — даже когда риск вакцины намного ниже риска болезни. Действие вакцинации ощущается более ответственным за любой исход, чем бездействие.',
        tip: 'При оценке вариантов относись к бездействию как к выбору. «Ничего не делать» — это решение с последствиями, а не нейтральная базовая линия. Применяй к бездействию те же стандарты, что к действию.',
      },
    },
  },
  {
    id: 'narrative-fallacy',
    order: 46,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Narrative Fallacy',
        hook: "It makes a better story. So it must be what happened.",
        body: "You impose coherent narratives on complex, random events. The story feels true because it's satisfying — it has a cause, a consequence, a lesson. But the story is a construction. Reality is usually messier, more random, and less meaningful than the story you've built around it.",
        example: "After a company succeeds: 'The visionary founder's bold strategy paid off.' After it fails: 'The arrogant founder ignored market signals.' Same decisions, different outcome, different story.",
        tip: "When a compelling narrative appears, ask: what evidence would look identical if the story were completely wrong? If nothing would look different — you're holding a narrative, not a finding.",
      },
      ru: {
        title: 'Ошибка нарратива',
        hook: 'Так лучше звучит история. Значит, именно так и было.',
        body: 'Ты накладываешь связные нарративы на сложные, случайные события. История кажется правдивой, потому что она удовлетворяет — в ней есть причина, следствие, урок. Но история — это конструкция. Реальность обычно более беспорядочна, случайна и менее значима, чем история, которую ты вокруг неё построил.',
        example: 'После успеха компании: «Смелая стратегия дальновидного основателя принесла плоды». После провала: «Высокомерный основатель игнорировал рыночные сигналы». Те же решения, разный исход, разные истории.',
        tip: 'Когда появляется убедительный нарратив, спроси: как выглядели бы доказательства, если бы история была полностью неверна? Если ничего не выглядело бы иначе — ты держишься за нарратив, а не за вывод.',
      },
    },
  },
  {
    id: 'social-comparison-bias',
    order: 47,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Social Comparison Bias',
        hook: "You'd rather hire someone worse than you than someone who might outperform you.",
        body: "You judge your own worth relative to others — and unconsciously make choices that protect your relative standing. You undermine people who threaten your position, hire people unlikely to surpass you, and feel worse about your own achievements when someone around you succeeds.",
        example: "Managers consistently rate candidates lower when those candidates have skills that overlap with and exceed the manager's own. It's not a conscious decision. It's threat response.",
        tip: "Surround yourself with people who are better than you at the things that matter. Your absolute performance matters; your relative ranking in your social circle doesn't.",
      },
      ru: {
        title: 'Предвзятость социального сравнения',
        hook: 'Ты скорее наймёшь кого-то хуже себя, чем того, кто может превзойти тебя.',
        body: 'Ты оцениваешь свою значимость относительно других — и неосознанно делаешь выборы, которые защищают твоё относительное положение. Ты подрываешь людей, угрожающих твоей позиции, нанимаешь тех, кто вряд ли тебя превзойдёт, и хуже себя чувствуешь, когда кто-то рядом добивается успеха.',
        example: 'Менеджеры систематически занижают оценку кандидатов, чьи навыки пересекаются с навыками менеджера и превосходят их. Это не сознательное решение. Это реакция на угрозу.',
        tip: 'Окружай себя людьми, которые лучше тебя в важных вещах. Важны твои абсолютные показатели; твой относительный рейтинг в социальном круге — нет.',
      },
    },
  },
  {
    id: 'unit-bias',
    order: 48,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Unit Bias',
        hook: "One portion feels like the right amount. Regardless of how big the portion is.",
        body: "You feel compelled to finish a unit — a plate, a bottle, an episode, a chapter — regardless of its actual size. The unit signals 'complete.' Your brain uses 'finishing the unit' as a proxy for 'enough.' Someone else decided the unit size. You just obeyed it.",
        example: "People eat more from large plates than small ones. Not because they were hungrier — because the plate was the unit. Finishing it signaled satisfaction, not the food itself.",
        tip: "Create your own units. Use a smaller plate. Split the episode. Decide in advance when the chapter ends. The unit is arbitrary — don't let someone else's arbitrary choice govern your consumption.",
      },
      ru: {
        title: 'Предвзятость единицы',
        hook: 'Одна порция кажется правильным количеством. Независимо от размера порции.',
        body: 'Ты чувствуешь необходимость закончить единицу — тарелку, бутылку, эпизод, главу — независимо от её фактического размера. Единица сигнализирует «завершено». Мозг использует «закончить единицу» как замену «достаточно». Кто-то другой решил размер единицы. Ты просто подчинился.',
        example: 'Люди едят больше с больших тарелок, чем с маленьких. Не потому что были голоднее — потому что тарелка была единицей. Доедание тарелки сигнализировало удовлетворение, а не сама еда.',
        tip: 'Создавай свои единицы. Используй тарелку меньшего размера. Останови эпизод на середине. Реши заранее, где заканчивается глава. Единица произвольна — не позволяй чужому произвольному выбору управлять твоим потреблением.',
      },
    },
  },
  {
    id: 'ambiguity-effect',
    order: 49,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Ambiguity Effect',
        hook: "You avoid options with unknown odds. Even when they're probably better.",
        body: "When the probability of an outcome is unknown, you avoid that option — even if the known-probability alternative is objectively worse. Uncertainty feels like danger. Known bad beats unknown maybe-good.",
        example: "Given a choice between a 50% chance of winning $100 or an unknown chance of winning $100, most people choose the known odds — even if the unknown odds might be better. The known feels safer.",
        tip: "Distinguish between risk (known odds) and uncertainty (unknown odds). Most real-world opportunities are uncertain, not risky. Avoiding them by default means avoiding most of the upside.",
      },
      ru: {
        title: 'Эффект неоднозначности',
        hook: 'Ты избегаешь вариантов с неизвестными шансами. Даже когда они, вероятно, лучше.',
        body: 'Когда вероятность исхода неизвестна, ты избегаешь этого варианта — даже если альтернатива с известной вероятностью объективно хуже. Неопределённость ощущается как опасность. Известное плохое лучше неизвестного возможно-хорошего.',
        example: 'Перед выбором между 50% шансом выиграть 100$ и неизвестным шансом выиграть 100$ большинство выбирают известные шансы — даже если неизвестные могут быть лучше. Известное ощущается безопаснее.',
        tip: 'Различай риск (известные шансы) и неопределённость (неизвестные шансы). Большинство реальных возможностей неопределённы, а не рискованны. Избегать их по умолчанию — значит избегать большей части потенциальных выгод.',
      },
    },
  },
  {
    id: 'cheerleader-effect',
    order: 50,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Cheerleader Effect',
        hook: "They look better in a group. When you see them alone, something shifts.",
        body: "Individual faces are judged as more attractive when seen as part of a group than when seen alone. The group average smooths out individual features. Your brain takes a shortcut: if the group looks good, the individuals must too.",
        example: "Photographs of the same people are consistently rated more attractive in group photos than in solo shots. The effect holds even when the surrounding faces are average.",
        tip: "Evaluate people individually, not contextually. The same principle applies beyond attractiveness — skills, ideas, and products look better when surrounded by similar things. Isolate before judging.",
      },
      ru: {
        title: 'Эффект группы поддержки',
        hook: 'В группе они выглядят лучше. Когда видишь их по отдельности, что-то меняется.',
        body: 'Отдельные лица оцениваются как более привлекательные, когда их видят как часть группы, а не по отдельности. Среднее группы сглаживает индивидуальные черты. Мозг принимает ярлык: если группа выглядит хорошо, значит и индивиды тоже.',
        example: 'Фотографии одних и тех же людей систематически оцениваются как более привлекательные на групповых фото, чем на одиночных. Эффект сохраняется, даже когда окружающие лица средние.',
        tip: 'Оценивай людей индивидуально, а не контекстуально. Тот же принцип применим не только к привлекательности: навыки, идеи и продукты выглядят лучше в окружении похожих вещей. Изолируй перед суждением.',
      },
    },
  },
  {
    id: 'denomination-effect',
    order: 51,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Denomination Effect',
        hook: "You'd break a $100 bill for $5 of groceries. The $5 bills go faster.",
        body: "People are less likely to spend large bills than the equivalent in smaller denominations — even though the value is identical. Large bills feel more 'real' as money. Small bills feel more like spending money. The physical form of money changes your relationship to it.",
        example: "Participants given one $20 bill spent it less readily than those given four $5 bills — even when explicitly told they had the same amount.",
        tip: "If you want to spend less, carry larger bills. If you want to see your budget clearly, pay in cash rather than card. The physical form of money isn't neutral — use it to your advantage.",
      },
      ru: {
        title: 'Эффект деноминации',
        hook: 'Ты разменяешь купюру в 5000 ради покупки на 300 рублей. Мелкие купюры уходят быстрее.',
        body: 'Люди менее склонны тратить крупные купюры, чем эквивалент в мелких — несмотря на идентичную ценность. Крупные купюры ощущаются более «реальными» как деньги. Мелкие — как расходные. Физическая форма денег меняет твоё отношение к ним.',
        example: 'Участники, которым дали одну купюру в 2000 рублей, тратили её менее охотно, чем те, кому дали четыре по 500 — даже когда им прямо говорили, что суммы равны.',
        tip: 'Если хочешь тратить меньше — носи крупные купюры. Если хочешь ясно видеть бюджет — плати наличными, а не картой. Физическая форма денег не нейтральна — используй это в своих интересах.',
      },
    },
  },
  {
    id: 'empathy-gap',
    order: 52,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Empathy Gap',
        hook: "You made a calm decision. Then emotions arrived and it stopped making sense.",
        body: "You underestimate how much your emotional state will influence your future decisions — and how little you can predict your behavior when in a different emotional state. Cold decisions don't account for hot moments. Hot moments don't account for cold reason.",
        example: "People consistently underestimate how much they'll eat when hungry, spend when excited, or say when angry. 'I would never do that' is a statement made from the wrong emotional state.",
        tip: "Make irreversible decisions when calm. Create automatic rules for emotional states — 'when angry, I wait 24 hours before responding.' Your future emotional self is a different person. Plan for them.",
      },
      ru: {
        title: 'Разрыв эмпатии',
        hook: 'Ты принял спокойное решение. Потом пришли эмоции, и оно перестало иметь смысл.',
        body: 'Ты недооцениваешь, насколько твоё эмоциональное состояние будет влиять на будущие решения — и насколько мало ты можешь предсказать своё поведение в другом эмоциональном состоянии. Холодные решения не учитывают горячие моменты. Горячие моменты не учитывают холодный разум.',
        example: 'Люди систематически недооценивают, сколько съедят, когда голодны, потратят, когда взволнованы, или скажут, когда злятся. «Я бы никогда этого не сделал» — утверждение, сделанное из неправильного эмоционального состояния.',
        tip: 'Принимай необратимые решения в спокойном состоянии. Создавай автоматические правила для эмоциональных состояний — «когда злюсь, жду 24 часа перед ответом». Твоё будущее эмоциональное «я» — другой человек. Планируй с учётом него.',
      },
    },
  },
  {
    id: 'just-world-hypothesis',
    order: 53,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Just-World Hypothesis',
        hook: "Something bad happened to them. You're looking for what they did to deserve it.",
        body: "You believe — unconsciously — that the world is fundamentally fair, and that people get what they deserve. This belief is psychologically comforting. It makes bad things seem predictable and avoidable. It also leads you to blame victims and ignore systemic causes.",
        example: "People tend to judge victims of crime, poverty, or illness as somehow responsible for their situation — because the alternative (random bad things happen to random people) is too threatening to believe.",
        tip: "When you find yourself wondering what someone 'did to deserve' misfortune — notice the belief. Ask what evidence would exist if the world were unfair. The answer usually includes most of what you see around you.",
      },
      ru: {
        title: 'Гипотеза справедливого мира',
        hook: 'С ними случилось что-то плохое. Ты ищешь, что они сделали, чтобы это заслужить.',
        body: 'Ты веришь — неосознанно — что мир в основе своей справедлив, и что люди получают то, что заслуживают. Это убеждение психологически утешительно. Оно делает плохие вещи предсказуемыми и предотвратимыми. Оно также заставляет тебя обвинять жертв и игнорировать системные причины.',
        example: 'Люди склонны судить жертв преступлений, бедности или болезни как несущих ответственность за свою ситуацию — потому что альтернатива (случайные плохие вещи случаются со случайными людьми) слишком угрожающа для принятия.',
        tip: 'Когда ловишь себя на вопросе, что кто-то «сделал, чтобы заслужить» несчастье — замечай это убеждение. Спроси, какие доказательства существовали бы, если бы мир был несправедлив. Ответ обычно включает большую часть того, что ты видишь вокруг.',
      },
    },
  },
  {
    id: 'functional-fixedness',
    order: 54,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Functional Fixedness',
        hook: "You can't solve the problem because you can only see the tool for what it's usually used for.",
        body: "You default to seeing objects, roles, and systems in terms of their conventional functions. When a problem requires a non-standard use, you can't see it. The more expert you become in a domain, the more this bias locks you in — expertise creates blind spots.",
        example: "In Duncker's candle problem, people struggle to use a tack box as a platform because they see it as a container, not a shelf. The solution is obvious once someone points it out. Before that, invisible.",
        tip: "When stuck on a problem, list every resource available and brainstorm non-standard uses. Ask: what else could this be? What else could this do? Function is assigned, not inherent.",
      },
      ru: {
        title: 'Функциональная фиксированность',
        hook: 'Ты не можешь решить проблему, потому что видишь инструмент только в его обычном применении.',
        body: 'Ты по умолчанию видишь объекты, роли и системы через призму их обычных функций. Когда проблема требует нестандартного использования — ты этого не видишь. Чем больше ты экспертизируешься в области, тем сильнее это ограничение: экспертиза создаёт слепые пятна.',
        example: 'В задаче Дункера со свечой люди не могут использовать коробку от кнопок как подставку, потому что видят её как контейнер, а не полку. Решение очевидно, как только кто-то на него указывает. До этого — невидимо.',
        tip: 'Когда застрял на проблеме, перечисли все доступные ресурсы и придумай нестандартные применения. Спроси: чем ещё это может быть? Что ещё это может делать? Функция назначена, а не присуща.',
      },
    },
  },
  {
    id: 'reactive-devaluation',
    order: 55,
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Reactive Devaluation',
        hook: "Your enemy proposed it. Suddenly it's a bad idea.",
        body: "You devalue proposals, concessions, or ideas simply because they come from someone you perceive as an adversary. The content doesn't change. Your relationship to the source does. The same idea from an ally is brilliant. From an enemy, it must have a catch.",
        example: "Identical peace proposals were rated more favorably when attributed to Israeli leaders than when attributed to Palestinian leaders by Israeli respondents — and vice versa. The proposal hadn't changed. The label had.",
        tip: "When evaluating ideas from sources you distrust, strip the source. Ask: if a neutral party proposed this, would I accept it? If yes, reactive devaluation is doing the work — not your actual judgment.",
      },
      ru: {
        title: 'Реактивное обесценивание',
        hook: 'Это предложил твой противник. Внезапно это плохая идея.',
        body: 'Ты обесцениваешь предложения, уступки или идеи просто потому, что они исходят от кого-то, кого ты воспринимаешь как противника. Содержание не меняется. Меняется твоё отношение к источнику. Та же идея от союзника — блестяща. От врага — в ней должен быть подвох.',
        example: 'Идентичные мирные предложения оценивались более благоприятно, когда их приписывали израильским лидерам, а не палестинским — израильскими респондентами, и наоборот. Предложение не изменилось. Изменился ярлык.',
        tip: 'Оценивая идеи из источников, которым не доверяешь, убери источник. Спроси: если бы нейтральная сторона предложила это, принял бы я? Если да — реактивное обесценивание делает работу, а не твоё реальное суждение.',
      },
    },
  },
];
