export const seedCards = [
  {
    id: 'confirmation-bias',
    release_date: '2026-05-01',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Confirmation Bias',
        hook: "You've already decided. Now you're just collecting evidence.",
        body: "Your brain doesn't look for truth — it looks for validation. You notice information that confirms your beliefs and ignore everything that doesn't. It feels like research. It's actually a filter.",
        example: "You think a colleague is incompetent. From now on, every mistake they make stands out. Every success goes unnoticed. You've built a case, not a picture.",
        tip: "Before deciding, spend 5 minutes actively looking for evidence that you're wrong. The discomfort you feel is the bias resisting.",
      },
      ru: {
        title: 'Предвзятость подтверждения',
        hook: 'Ты уже решил. Теперь просто собираешь доказательства.',
        body: 'Мозг ищет не правду — он ищет подтверждение. Ты замечаешь факты, которые совпадают с твоими убеждениями, и фильтруешь всё остальное. Это не исследование. Это самообман с видом исследования.',
        example: 'Ты считаешь коллегу некомпетентным. Теперь каждая его ошибка бросается в глаза. Каждый успех проходит мимо. Ты строишь обвинение, а не картину реальности.',
        tip: 'Перед любым важным решением потрать 5 минут на поиск доказательств, что ты неправ. Дискомфорт, который ты почувствуешь — это и есть предвзятость.',
      },
    },
  },
  {
    id: 'anchoring-effect',
    release_date: '2026-05-02',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Anchoring Effect',
        hook: "That price feels reasonable. Only because they showed you a bigger one first.",
        body: "The first number you hear becomes an anchor. Every estimate, negotiation, and judgment you make gets pulled toward it — even if the anchor was chosen at random. You think you're reasoning. You're calibrating.",
        example: "A store marks a jacket 'was $400, now $180'. You feel like you're getting a deal. The original price may have been invented specifically to anchor you at $180.",
        tip: "Ask yourself: if I'd never heard the first number, would this still feel reasonable? If your answer changes — you were anchored.",
      },
      ru: {
        title: 'Эффект якоря',
        hook: 'Цена кажется разумной. Только потому что сначала показали бо́льшую.',
        body: 'Первое число, которое ты услышал, становится якорем. Все дальнейшие оценки притягиваются к нему — даже если якорь был выбран случайно. Тебе кажется, что ты рассуждаешь. На самом деле — калибруешься.',
        example: 'Пальто «было 20 000, теперь 9 000». Ощущение выгодной покупки. Исходная цена могла быть выдумана именно для того, чтобы якорь поставить на 9 000.',
        tip: 'Спроси себя: если бы я не слышал первое число, цена всё равно казалась бы мне нормальной? Если ответ меняется — ты попался.',
      },
    },
  },
  {
    id: 'dunning-kruger',
    release_date: '2026-05-03',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Dunning-Kruger Effect',
        hook: "The less you know, the more confident you are.",
        body: "Beginners overestimate their competence because they don't know enough to know what they're missing. Experts underestimate theirs because they're constantly aware of complexity. Confidence and knowledge move in opposite directions — at first.",
        example: "After two weeks of investing, someone is certain they've found a strategy. After twenty years, they're far more cautious. Same domain. Inverted confidence.",
        tip: "When you feel absolutely certain about something complex, treat it as a warning sign — not a green light.",
      },
      ru: {
        title: 'Эффект Даннинга–Крюгера',
        hook: 'Чем меньше знаешь — тем увереннее себя чувствуешь.',
        body: 'Новичок переоценивает себя, потому что не знает, чего не знает. Эксперт недооценивает, потому что видит всю сложность. Уверенность и знание движутся в противоположных направлениях — поначалу.',
        example: 'Через две недели торговли на бирже человек уверен, что нашёл стратегию. Через двадцать лет — он стал намного осторожнее. Та же сфера. Перевёрнутая уверенность.',
        tip: 'Когда чувствуешь абсолютную уверенность в чём-то сложном — это тревожный знак, а не зелёный свет.',
      },
    },
  },
  {
    id: 'survivorship-bias',
    release_date: '2026-05-04',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Survivorship Bias',
        hook: "You're learning from the winners. The losers aren't here to talk.",
        body: "We study what survived and ignore what didn't — because failures are invisible. This makes us draw wildly wrong conclusions about what works. Every lesson learned from winners contains a silent, invisible counter-lesson from those who tried the same thing and failed.",
        example: "Startup advice comes almost entirely from founders who succeeded. Thousands tried the same moves and failed. Their stories never became books.",
        tip: "For every success story, ask: what would the failure stories look like? Are they telling a different story?",
      },
      ru: {
        title: 'Ошибка выжившего',
        hook: 'Ты учишься у победителей. Проигравших здесь нет.',
        body: 'Мы изучаем выживших и игнорируем тех, кто не выжил — потому что провалы невидимы. Это заставляет нас делать неверные выводы о том, что работает. Каждый урок победителя содержит молчаливый контрурок тех, кто делал то же самое и провалился.',
        example: 'Советы стартапов почти всегда исходят от основателей, которые преуспели. Тысячи попробовали те же приёмы и потерпели неудачу. Их истории не стали книгами.',
        tip: 'За каждой историей успеха спроси: как выглядят истории провалов? Они говорят что-то другое?',
      },
    },
  },
  {
    id: 'availability-heuristic',
    release_date: '2026-05-05',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Availability Heuristic',
        hook: "You think it's more likely because it was on the news.",
        body: "Your brain estimates probability by how easily examples come to mind. Vivid, recent, emotional events feel more common than they are. Boring statistics feel impossible. The more dramatic a scenario, the more dangerous it seems — regardless of actual frequency.",
        example: "After a shark attack makes headlines, beach attendance drops. Car accidents kill vastly more people per week. Nobody cancels road trips.",
        tip: "When estimating risk, look up actual statistics. Your gut is using drama as a proxy for data.",
      },
      ru: {
        title: 'Эвристика доступности',
        hook: 'Это кажется более вероятным, потому что об этом писали в новостях.',
        body: 'Мозг оценивает вероятность по лёгкости, с которой приходят примеры. Яркие, свежие, эмоциональные события кажутся более распространёнными. Скучная статистика — невозможной. Чем драматичнее сценарий, тем он кажется опаснее — вне зависимости от реальной частоты.',
        example: 'После сообщения об атаке акулы посещаемость пляжей падает. ДТП убивают значительно больше людей в неделю. Никто не отменяет поездки на машине.',
        tip: 'Когда оцениваешь риск — найди реальную статистику. Твоя интуиция использует драму вместо данных.',
      },
    },
  },
  {
    id: 'sunk-cost-fallacy',
    release_date: '2026-05-06',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Sunk Cost Fallacy',
        hook: "You keep going because you've already put too much in to stop.",
        body: "Money spent, time invested, effort given — none of it should influence future decisions. It's gone either way. But your brain treats past investment as a reason to continue, even when stopping is clearly the better choice.",
        example: "You stay in a job you hate for three years because you've already been there three years. That logic costs you three more.",
        tip: "Ask: if I were starting fresh today, would I choose this? If not, you're not being loyal — you're being held hostage by sunk costs.",
      },
      ru: {
        title: 'Ошибка невозвратных затрат',
        hook: 'Ты продолжаешь, потому что уже слишком много вложил, чтобы остановиться.',
        body: 'Потраченные деньги, вложенное время, приложенные усилия — всё это не должно влиять на будущие решения. Они ушли в любом случае. Но мозг воспринимает прошлые инвестиции как причину продолжать — даже когда остановиться очевидно лучше.',
        example: 'Ты остаёшься на нелюбимой работе три года, потому что уже три года там. Эта логика обходится тебе ещё тремя.',
        tip: 'Спроси: если бы я начинал с нуля сегодня, я бы выбрал это? Если нет — ты не верен себе. Ты в заложниках у прошлых трат.',
      },
    },
  },
  {
    id: 'framing-effect',
    release_date: '2026-05-07',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Framing Effect',
        hook: "How something is said changes what you decide. Every single time.",
        body: "Identical information, presented differently, produces different choices. '90% survival rate' and '10% death rate' are mathematically the same. They don't feel the same. Whoever controls the frame controls the decision.",
        example: "Ground beef labeled '80% lean' sells better than '20% fat'. Same product. Different frame. Different behavior.",
        tip: "Restate every important choice in its opposite frame before deciding. If your answer changes, the frame was doing the deciding — not you.",
      },
      ru: {
        title: 'Эффект фрейминга',
        hook: 'То, как сказано, меняет то, что ты решаешь. Каждый раз.',
        body: 'Одинаковая информация, поданная по-разному, приводит к разным выборам. «90% выживших» и «10% смертности» математически идентичны. На ощущение — нет. Кто контролирует формулировку — контролирует решение.',
        example: 'Говяжий фарш «80% мяса» продаётся лучше, чем «20% жира». Тот же продукт. Другой фрейм. Другие продажи.',
        tip: 'Переформулируй каждое важное решение в противоположном ключе перед тем, как решить. Если ответ меняется — решал фрейм, а не ты.',
      },
    },
  },
  {
    id: 'bandwagon-effect',
    release_date: '2026-05-08',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Bandwagon Effect',
        hook: "You changed your mind because everyone else did.",
        body: "The more people believe something, the more you're inclined to believe it too — regardless of evidence. Popularity becomes proof. Consensus becomes truth. Your opinion is partly a headcount.",
        example: "Crypto surges because everyone is buying. You buy because everyone is buying. The price crashes. Everyone was just watching everyone else.",
        tip: "Ask: would I believe this if only three people agreed? If not, you're not reasoning — you're following.",
      },
      ru: {
        title: 'Эффект подножки',
        hook: 'Ты изменил мнение, потому что все остальные изменили.',
        body: 'Чем больше людей во что-то верят, тем сильнее ты склонен верить тоже — вне зависимости от доказательств. Популярность становится доказательством. Консенсус — истиной. Твоё мнение отчасти — это подсчёт голосов.',
        example: 'Криптовалюта растёт, потому что все покупают. Ты покупаешь, потому что все покупают. Цена рушится. Все просто смотрели друг на друга.',
        tip: 'Спроси: я бы верил в это, если бы согласились только трое? Если нет — ты не рассуждаешь, ты следуешь.',
      },
    },
  },
  {
    id: 'hindsight-bias',
    release_date: '2026-05-09',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Hindsight Bias',
        hook: "After it happened, you were sure you knew it would.",
        body: "Once an event occurs, it feels inevitable in retrospect. You remember your prediction as more accurate than it was. This makes you overconfident about future predictions and blind to how uncertain the past actually was.",
        example: "After the financial crisis: 'Obviously the housing market was going to collapse.' Before: almost nobody said so publicly.",
        tip: "Keep a prediction log. Write down what you think will happen before it does. The gap between your forecast and your memory will surprise you.",
      },
      ru: {
        title: 'Предвзятость ретроспективы',
        hook: 'После того как всё случилось, ты был уверен, что знал заранее.',
        body: 'Когда событие произошло, оно кажется неизбежным задним числом. Ты помнишь свой прогноз точнее, чем он был. Это делает тебя самоуверенным в будущих прогнозах и слепым к тому, насколько неопределённым было прошлое.',
        example: 'После финансового кризиса: «Очевидно же, что рынок недвижимости должен был рухнуть.» До кризиса: почти никто этого публично не говорил.',
        tip: 'Веди журнал прогнозов. Записывай, что, по-твоему, произойдёт — до того как произойдёт. Разрыв между прогнозом и памятью тебя удивит.',
      },
    },
  },
  {
    id: 'halo-effect',
    release_date: '2026-05-10',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Halo Effect',
        hook: "You think they're smart because they're attractive.",
        body: "One positive trait — looks, charisma, status — bleeds into your assessment of everything else about a person. You assume competence from confidence, intelligence from appearance, honesty from charm. The halo makes you stop looking.",
        example: "Attractive defendants receive lighter sentences on average. Juries aren't corrupt — they're human. The halo does the judging.",
        tip: "Evaluate traits independently. Being good at one thing is not evidence of being good at anything else.",
      },
      ru: {
        title: 'Эффект ореола',
        hook: 'Ты думаешь, что он умный, потому что он привлекательный.',
        body: 'Одно положительное качество — внешность, харизма, статус — распространяется на всё остальное, что ты думаешь о человеке. Ты принимаешь уверенность за компетентность, внешность — за интеллект, обаяние — за честность. Ореол заставляет тебя прекратить смотреть.',
        example: 'Привлекательные подсудимые в среднем получают более мягкие приговоры. Присяжные не коррумпированы — они люди. Ореол судит вместо них.',
        tip: 'Оценивай качества независимо друг от друга. Быть хорошим в одном — не доказательство хороших качеств в другом.',
      },
    },
  },
  {
    id: 'status-quo-bias',
    release_date: '2026-05-11',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Status Quo Bias',
        hook: "You're not choosing to stay. You're avoiding the effort of leaving.",
        body: "The current state feels like the default. Any change requires justification; staying doesn't. So you stay — in jobs, relationships, habits, subscriptions — not because they're good, but because leaving takes effort and the status quo takes none.",
        example: "Most people never change their default settings. Apps, insurance plans, pension funds — defaults win not by merit but by inertia.",
        tip: "Periodically ask: if I were choosing this from scratch today, would I? If the honest answer is no — you're not choosing. You're drifting.",
      },
      ru: {
        title: 'Предвзятость статус-кво',
        hook: 'Ты не выбираешь остаться. Ты избегаешь усилий, чтобы уйти.',
        body: 'Текущее состояние воспринимается как данность. Любое изменение требует обоснования; оставаться — нет. Поэтому ты остаёшься — в работе, отношениях, привычках, подписках — не потому что хорошо, а потому что уходить требует усилий, а статус-кво — нет.',
        example: 'Большинство людей никогда не меняют настройки по умолчанию. Приложения, страховки, пенсионные фонды — дефолты побеждают не достоинствами, а инерцией.',
        tip: 'Периодически спрашивай: если бы я выбирал это с нуля сегодня — выбрал бы? Если честный ответ — нет, ты не выбираешь. Ты дрейфуешь.',
      },
    },
  },
  {
    id: 'fundamental-attribution-error',
    release_date: '2026-05-12',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Fundamental Attribution Error',
        hook: "When they fail, it's their fault. When you fail, it's the circumstances.",
        body: "You judge other people's behavior by their character and ignore the situation they're in. You judge your own behavior by the situation and downplay your character. The same action means something different depending on who performed it.",
        example: "Someone cuts you off in traffic: 'What an aggressive driver.' You cut someone off: 'I was running late and the lane was confusing.'",
        tip: "Before judging someone's behavior, ask what situational pressures they might be under. Apply the same generosity you give yourself.",
      },
      ru: {
        title: 'Фундаментальная ошибка атрибуции',
        hook: 'Когда они ошибаются — это их вина. Когда ты — обстоятельства.',
        body: 'Поведение других людей ты оцениваешь через их характер и игнорируешь ситуацию. Своё собственное поведение — через ситуацию и преуменьшаешь роль характера. Одно и то же действие означает разное в зависимости от того, кто его совершил.',
        example: 'Кто-то подрезает тебя на дороге: «Какой агрессивный водитель». Ты подрезаешь кого-то: «Опаздывал, разметка была непонятная».',
        tip: 'Перед тем как судить о чьём-то поведении, спроси: под каким ситуативным давлением они могут находиться? Прояви ту же щедрость, что и к себе.',
      },
    },
  },
  {
    id: 'planning-fallacy',
    release_date: '2026-05-13',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Planning Fallacy',
        hook: "It'll take two weeks. It'll take three months.",
        body: "We consistently underestimate how long tasks will take, how much they'll cost, and how many things will go wrong — even when we have direct experience with similar projects going over time and budget. Optimism overrides memory.",
        example: "The Sydney Opera House was planned for 4 years and $7M. It took 14 years and $102M. Every major infrastructure project has a version of this story.",
        tip: "Use reference class forecasting: find similar past projects and use their actual completion times as your baseline — not your optimistic plan.",
      },
      ru: {
        title: 'Ошибка планирования',
        hook: 'Займёт две недели. Займёт три месяца.',
        body: 'Мы постоянно недооцениваем, сколько займут задачи, сколько будет стоить и сколько всего пойдёт не так — даже когда у нас есть прямой опыт с похожими проектами, которые выбивались из сроков и бюджета. Оптимизм перекрывает память.',
        example: 'Сиднейский оперный театр планировали построить за 4 года и $7 млн. Строили 14 лет и потратили $102 млн. У каждого крупного проекта есть своя версия этой истории.',
        tip: 'Используй прогнозирование по референс-классу: найди похожие прошлые проекты и используй их реальные сроки как отправную точку — а не свой оптимистичный план.',
      },
    },
  },
  {
    id: 'curse-of-knowledge',
    release_date: '2026-05-14',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Curse of Knowledge',
        hook: "You can't remember what it was like not to know this.",
        body: "Once you know something, you can't imagine not knowing it. This makes you a bad teacher, a bad communicator, and a bad designer — because you consistently overestimate how much your audience already understands.",
        example: "In a study, people tapped out famous songs with their fingers. They estimated listeners would recognize 50% of songs. The actual rate was 2.5%. The tapper hears the full melody in their head. The listener hears random taps.",
        tip: "When explaining anything, assume your audience knows nothing. Then assume even less. You'll still probably overshoot.",
      },
      ru: {
        title: 'Проклятие знания',
        hook: 'Ты уже не можешь вспомнить, каково это — не знать этого.',
        body: 'Узнав что-то, ты не можешь представить, как это — не знать. Это делает тебя плохим учителем, плохим коммуникатором и плохим дизайнером — потому что ты постоянно переоцениваешь, сколько твоя аудитория уже понимает.',
        example: 'В одном исследовании люди отстукивали пальцами известные мелодии. Они считали, что слушатели узнают 50% песен. Реальный показатель — 2,5%. Тот, кто стучит, слышит в голове всю мелодию. Слушатель слышит случайные удары.',
        tip: 'Объясняя что-либо, предполагай, что аудитория не знает ничего. Потом предполагай ещё меньше. Ты всё равно, скорее всего, перестараешься.',
      },
    },
  },
  {
    id: 'gamblers-fallacy',
    release_date: '2026-05-15',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: "Gambler's Fallacy",
        hook: "It's been tails five times. Heads is due.",
        body: "Random events don't have memory. A coin doesn't know it's been tails five times. Each flip is independent. But your brain detects patterns even where none exist — and expects the universe to 'balance out.'",
        example: "Roulette lands on red seven times in a row. Bets on black surge. The wheel doesn't know. The casino does.",
        tip: "In any independent random process, past outcomes tell you nothing about the next one. 'Due' is not a real concept in probability.",
      },
      ru: {
        title: 'Ошибка игрока',
        hook: 'Пять раз подряд решка. Орёл уже должен выпасть.',
        body: 'Случайные события не имеют памяти. Монета не знает, что пять раз была решка. Каждый бросок независим. Но мозг видит паттерны там, где их нет — и ожидает, что вселенная «уравновесится».',
        example: 'Рулетка семь раз подряд выдаёт красное. Ставки на чёрное резко растут. Колесо не знает. Казино знает.',
        tip: 'В любом независимом случайном процессе прошлые результаты ничего не говорят о следующем. «Пора» — не реальная концепция в теории вероятностей.',
      },
    },
  },
  {
    id: 'loss-aversion',
    release_date: '2026-05-16',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Loss Aversion',
        hook: "Losing $100 hurts more than winning $100 feels good.",
        body: "Losses feel roughly twice as painful as equivalent gains feel pleasurable. This asymmetry warps every decision involving risk — making you hold losing investments, avoid beneficial risks, and stay in bad situations just to avoid locking in a loss.",
        example: "You hold a losing stock hoping it'll recover rather than selling and moving on. The rational move is clear. The emotional math doesn't add up that way.",
        tip: "When facing a decision, ask: am I making this choice based on what's best going forward, or to avoid the pain of admitting a loss?",
      },
      ru: {
        title: 'Неприятие потерь',
        hook: 'Потерять 100 долларов больнее, чем приятно их выиграть.',
        body: 'Потери ощущаются примерно вдвое болезненнее, чем равнозначные приобретения приятны. Эта асимметрия искажает каждое решение, связанное с риском — заставляя держать убыточные вложения, избегать полезных рисков и оставаться в плохих ситуациях только чтобы не фиксировать потерю.',
        example: 'Ты держишь убыточную акцию в надежде, что она восстановится, вместо того чтобы продать и двигаться дальше. Рациональный выбор очевиден. Эмоциональная математика так не считает.',
        tip: 'Принимая решение, спроси: я делаю этот выбор исходя из того, что лучше в будущем, или чтобы избежать боли от признания потери?',
      },
    },
  },
  {
    id: 'ikea-effect',
    release_date: '2026-05-17',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'IKEA Effect',
        hook: "You love it because you built it. Not because it's good.",
        body: "When you put effort into creating something, you overvalue it — disproportionately to its actual quality. Labor creates love. The problem is, your attachment blinds you to its real flaws and makes you resistant to criticism.",
        example: "Founders can't kill features they built. Parents can't see their children's faults clearly. The work you did is now inseparable from the judgment you make about it.",
        tip: "Get an outsider's honest assessment before concluding your creation is exceptional. Effort invested is not evidence of quality produced.",
      },
      ru: {
        title: 'Эффект ИКЕА',
        hook: 'Тебе это нравится, потому что ты это сделал. Не потому что это хорошо.',
        body: 'Когда ты вкладываешь усилия в создание чего-либо, ты переоцениваешь это — непропорционально реальному качеству. Труд порождает привязанность. Проблема в том, что эта привязанность ослепляет тебя к реальным недостаткам и делает тебя устойчивым к критике.',
        example: 'Основатели не могут удалить функции, которые сами создали. Родители не видят недостатков своих детей объективно. Твоя работа неотделима от суждения, которое ты о ней выносишь.',
        tip: 'Получи честную оценку стороннего человека, прежде чем решить, что твоё творение исключительно. Вложенные усилия — не доказательство качества результата.',
      },
    },
  },
  {
    id: 'spotlight-effect',
    release_date: '2026-05-18',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Spotlight Effect',
        hook: "Nobody noticed. You were the only one watching.",
        body: "You overestimate how much other people notice and remember about you — your mistakes, your appearance, your awkward moment. In reality, everyone is too busy monitoring their own spotlight to pay sustained attention to yours.",
        example: "You spill coffee on your shirt before a meeting. You're convinced everyone noticed. Three hours later, nobody mentions it. They were thinking about their own problems.",
        tip: "Other people are not your audience. They're the main character in their own story, dealing with their own spotlight.",
      },
      ru: {
        title: 'Эффект прожектора',
        hook: 'Никто не заметил. Ты единственный, кто смотрел.',
        body: 'Ты переоцениваешь, насколько другие замечают и помнят о тебе — твои ошибки, внешность, неловкий момент. На самом деле все слишком заняты наблюдением за собственным прожектором, чтобы устойчиво следить за твоим.',
        example: 'Ты проливаешь кофе на рубашку перед встречей. Уверен, что все заметили. Через три часа никто не упоминает. Они думали о своих проблемах.',
        tip: 'Другие люди — не твоя аудитория. Они главные герои в собственной истории, занятые своим прожектором.',
      },
    },
  },
  {
    id: 'false-consensus-effect',
    release_date: '2026-05-19',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'False Consensus Effect',
        hook: "You think most people agree with you. They don't.",
        body: "You overestimate how common your opinions, values, and behaviors are. Because your social environment reflects back beliefs similar to your own, you mistake your bubble for the world. Your normal is not the baseline.",
        example: "People who don't recycle believe most people don't recycle. People who do recycle believe most people do. Both are wrong. Both feel certain.",
        tip: "Before assuming your view is the majority view, find actual data. Your social circle is not a representative sample of humanity.",
      },
      ru: {
        title: 'Эффект ложного консенсуса',
        hook: 'Ты думаешь, что большинство людей согласны с тобой. Это не так.',
        body: 'Ты переоцениваешь, насколько распространены твои мнения, ценности и поведение. Потому что твоё социальное окружение отражает похожие взгляды, ты принимаешь свой пузырь за весь мир. Твоя норма — не общая норма.',
        example: 'Люди, которые не сортируют мусор, считают, что большинство не сортирует. Те, кто сортирует — что большинство сортирует. Оба неправы. Оба уверены.',
        tip: 'Перед тем как считать свою точку зрения мнением большинства, найди реальные данные. Твой социальный круг — не репрезентативная выборка человечества.',
      },
    },
  },
  {
    id: 'recency-bias',
    release_date: '2026-05-20',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Recency Bias',
        hook: "What just happened feels like what will always happen.",
        body: "Recent events are weighted too heavily in your predictions and judgments. A good year makes the future feel bright. A bad week makes everything feel hopeless. Your brain mistakes 'just happened' for 'most representative.'",
        example: "After a market crash, investors predict more crashes. After a bull run, they predict more gains. Both predictions are shaped by recency, not evidence.",
        tip: "Deliberately look at longer time horizons before forming judgments. Recent history is not a reliable predictor — it's just the loudest signal right now.",
      },
      ru: {
        title: 'Предвзятость к недавнему',
        hook: 'То, что только что случилось, кажется тем, что будет всегда.',
        body: 'Недавним событиям придаётся слишком большой вес в прогнозах и суждениях. Хороший год делает будущее светлым. Плохая неделя делает всё безнадёжным. Мозг путает «только что случилось» с «наиболее показательным».',
        example: 'После обвала рынка инвесторы прогнозируют новые обвалы. После роста — новый рост. Оба прогноза сформированы недавностью, а не доказательствами.',
        tip: 'Намеренно смотри на более длинные горизонты перед формированием суждений. Недавняя история — не надёжный предиктор. Это просто самый громкий сигнал прямо сейчас.',
      },
    },
  },
  {
    id: 'optimism-bias',
    release_date: '2026-05-21',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Optimism Bias',
        hook: "You think bad things are more likely to happen to other people.",
        body: "Most people believe they're less likely than average to get divorced, have a car accident, develop cancer, or lose their job. Statistically, we can't all be below average. The bias is especially dangerous because it feels like confidence.",
        example: "80% of drivers consider themselves above average. Half of them are wrong. The same math applies to your business, your health, your relationships.",
        tip: "When making plans, actively force yourself to imagine failure scenarios. Not to be pessimistic — to be accurate.",
      },
      ru: {
        title: 'Оптимистическая предвзятость',
        hook: 'Ты думаешь, что плохие вещи чаще случаются с другими людьми.',
        body: 'Большинство людей считают, что они с меньшей вероятностью разведутся, попадут в ДТП, заболеют раком или потеряют работу — по сравнению со средним. Статистически мы не можем все быть ниже среднего. Предвзятость особенно опасна, потому что ощущается как уверенность.',
        example: '80% водителей считают себя выше среднего. Половина из них ошибается. Та же математика применима к твоему бизнесу, здоровью, отношениям.',
        tip: 'При составлении планов намеренно заставь себя представить сценарии провала. Не чтобы быть пессимистом — чтобы быть точным.',
      },
    },
  },
  {
    id: 'self-serving-bias',
    release_date: '2026-05-22',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Self-Serving Bias',
        hook: "Your successes are your talent. Your failures are bad luck.",
        body: "You attribute positive outcomes to your own skill and effort, and negative outcomes to external factors. This protects your self-esteem but prevents you from learning accurately from failure — and makes you credit yourself with luck.",
        example: "Project succeeds: 'I worked hard and made smart decisions.' Project fails: 'The market timing was off and the team let me down.'",
        tip: "After a failure, write down three things you personally did that contributed to it before blaming anything external. The truth is usually shared.",
      },
      ru: {
        title: 'Самооправдательная предвзятость',
        hook: 'Твои успехи — это твой талант. Твои неудачи — невезение.',
        body: 'Положительные результаты ты объясняешь собственными умениями и усилиями, а отрицательные — внешними факторами. Это защищает самооценку, но мешает точно учиться на неудачах — и заставляет тебя присваивать себе заслуги удачи.',
        example: 'Проект успешен: «Я усердно работал и принимал умные решения». Проект провалился: «Время было неподходящим и команда подвела».',
        tip: 'После неудачи запиши три вещи, которые ты лично сделал и которые к ней привели — прежде чем винить что-то внешнее. Правда обычно распределена.',
      },
    },
  },
  {
    id: 'in-group-bias',
    release_date: '2026-05-23',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'In-Group Bias',
        hook: "You're more forgiving of people who are like you.",
        body: "You favor members of your own group — your nationality, profession, sports team, political tribe — and judge them by different standards than outsiders. The same behavior looks reasonable from your group and suspicious from theirs.",
        example: "Politicians from your party 'made a difficult call.' Politicians from the other party 'acted in bad faith.' The action was identical.",
        tip: "Before judging someone's behavior, swap the group label and ask if you'd feel the same way. If not, you're applying a double standard.",
      },
      ru: {
        title: 'Предвзятость своей группы',
        hook: 'Ты более снисходителен к людям, которые похожи на тебя.',
        body: 'Ты отдаёшь предпочтение членам своей группы — своей национальности, профессии, спортивной команде, политическому лагерю — и судишь их по другим стандартам, чем посторонних. Одно и то же поведение выглядит разумным от своей группы и подозрительным от чужой.',
        example: 'Политики из твоей партии «приняли трудное решение». Политики из другой «действовали недобросовестно». Действие было идентичным.',
        tip: 'Прежде чем осуждать чьё-то поведение, поменяй групповой ярлык и спроси, чувствовал бы ты то же самое. Если нет — ты применяешь двойной стандарт.',
      },
    },
  },
  {
    id: 'normalcy-bias',
    release_date: '2026-05-24',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Normalcy Bias',
        hook: "Something is clearly wrong. You're waiting to see if it gets worse.",
        body: "When faced with a potential disaster, your brain defaults to assuming things will continue as normal. You underestimate both the probability of a crisis and the severity of its impact — and delay action until the evidence is undeniable. By then, it's often too late.",
        example: "People in burning buildings spend precious minutes gathering belongings instead of evacuating. Normalcy bias tells them it probably isn't that serious.",
        tip: "When warning signs appear, act on limited information. The cost of a false alarm is almost always lower than the cost of acting too late.",
      },
      ru: {
        title: 'Предвзятость нормальности',
        hook: 'Что-то явно идёт не так. Ты ждёшь, станет ли хуже.',
        body: 'Столкнувшись с потенциальной катастрофой, мозг по умолчанию предполагает, что всё продолжится как обычно. Ты недооцениваешь и вероятность кризиса, и серьёзность его последствий — и откладываешь действия до тех пор, пока доказательства не станут неопровержимыми. К тому времени часто уже слишком поздно.',
        example: 'Люди в горящих зданиях тратят драгоценные минуты на сбор вещей вместо эвакуации. Предвзятость нормальности говорит им, что всё, наверное, не так серьёзно.',
        tip: 'Когда появляются тревожные признаки, действуй при ограниченной информации. Цена ложной тревоги почти всегда ниже цены слишком позднего действия.',
      },
    },
  },
  {
    id: 'zero-risk-bias',
    release_date: '2026-05-25',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Zero-Risk Bias',
        hook: "You'd rather eliminate a small risk completely than reduce a bigger one significantly.",
        body: "Eliminating a risk entirely feels psychologically satisfying in a way that reducing a risk doesn't — even if the reduction saves more lives, money, or harm. Zero has emotional appeal beyond its mathematical value.",
        example: "People prefer a policy that eliminates 1 death from cause A over one that prevents 10 deaths from cause B. Zero deaths from A feels like a win. Ten fewer deaths from B feels abstract.",
        tip: "When evaluating risk-reduction options, focus on expected value — total risk reduced — not on which option sounds more complete.",
      },
      ru: {
        title: 'Предвзятость нулевого риска',
        hook: 'Ты предпочтёшь полностью устранить маленький риск, чем значительно снизить большой.',
        body: 'Полное устранение риска ощущается психологически удовлетворяющим так, как снижение риска — нет. Даже если снижение сохраняет больше жизней, денег или предотвращает больший вред. Ноль имеет эмоциональную привлекательность, выходящую за рамки математической ценности.',
        example: 'Люди предпочитают политику, которая устраняет 1 смерть от причины A, той, что предотвращает 10 смертей от причины B. Ноль смертей от A ощущается как победа. Десять меньше от B — абстракция.',
        tip: 'При оценке вариантов снижения риска фокусируйся на ожидаемой ценности — общем сниженном риске — а не на том, какой вариант звучит более полным.',
      },
    },
  },
  {
    id: 'hyperbolic-discounting',
    release_date: '2026-05-26',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Hyperbolic Discounting',
        hook: "$100 now beats $150 in a month. Every time.",
        body: "You overvalue immediate rewards relative to future ones — and the degree of overvaluation is irrational and inconsistent. You'll wait a year for a 10% bonus, but not a week for the same 10%. The closer the reward, the more distorted your judgment becomes.",
        example: "You'll start the diet on Monday. Every Sunday night for six months. The future self who benefits always seems capable of handling the sacrifice. The present self wants the cake.",
        tip: "When making decisions with future consequences, ask what your future self will think of this choice. Then weight that answer more than your current preference.",
      },
      ru: {
        title: 'Гиперболическое дисконтирование',
        hook: '100 долларов сейчас лучше, чем 150 через месяц. Всегда.',
        body: 'Ты переоцениваешь немедленные вознаграждения относительно будущих — и степень переоценки иррациональна и непоследовательна. Ты подождёшь год ради 10% бонуса, но не неделю ради того же 10%. Чем ближе награда — тем сильнее искажается суждение.',
        example: 'Ты начнёшь диету в понедельник. Каждое воскресенье вечером на протяжении шести месяцев. Будущее «я», которое получит выгоду, всегда кажется способным на жертву. Нынешнее «я» хочет торт.',
        tip: 'Принимая решения с будущими последствиями, спроси, что твоё будущее «я» подумает об этом выборе. Затем взвесь этот ответ больше, чем текущее предпочтение.',
      },
    },
  },
  {
    id: 'bystander-effect',
    release_date: '2026-05-27',
    category: 'cognitive_biases',
    i18n: {
      en: {
        title: 'Bystander Effect',
        hook: "You didn't help because you assumed someone else would.",
        body: "The more people present in an emergency, the less likely any individual is to help. Responsibility diffuses across the crowd. Everyone assumes someone else is more qualified, more aware, or more responsible. Nobody acts.",
        example: "Kitty Genovese was attacked in New York with 38 witnesses. Almost no one called the police. Each assumed others had already done so.",
        tip: "In emergencies, don't wait for consensus. Point at one specific person and say 'you — call an ambulance.' Diffused responsibility only dissolves when it becomes personal.",
      },
      ru: {
        title: 'Эффект свидетеля',
        hook: 'Ты не помог, потому что думал, что кто-нибудь другой поможет.',
        body: 'Чем больше людей присутствует при чрезвычайной ситуации, тем меньше вероятность, что кто-то из них поможет. Ответственность рассредоточивается по толпе. Каждый предполагает, что кто-то другой более квалифицирован, более осведомлён или более ответственен. Никто не действует.',
        example: 'На Китти Дженовезе напали в Нью-Йорке при 38 свидетелях. Почти никто не вызвал полицию. Каждый думал, что другие уже это сделали.',
        tip: 'В чрезвычайных ситуациях не жди консенсуса. Укажи на конкретного человека и скажи: «Ты — вызови скорую». Размытая ответственность растворяется только тогда, когда становится личной.',
      },
    },
  },
];
