// Локальный seed для Cavil. В продакшене карточки приходят из Firestore
// (collection `fallacies`); seed работает как offline fallback.
//
// Schema (двойной flip — UX 2):
//   FRONT:  hook
//   MID:    body + example
//   BACK:   counter_hook + counter_body + counter_example + tip
//
// Примеры намеренно политически нейтральные, гипотетические или из
// бизнес/быта.

export const seedCards = [
  {
    id: 'ad-hominem',
    order: 1,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Ad Hominem',
        hook: "He's wrong because of who he is. Not because of what he said.",
        body: "Instead of attacking the argument, you attack the person making it. The argument's truth value doesn't change based on who delivers it — but the audience's perception does. Cheap, common, often invisible.",
        example: "'Your idea about the budget is naive — you're only 24.' Age has no bearing on whether the budget math works. The attack pretends to be an evaluation.",
        counter_hook: "I'm asking about the argument. You're talking about me.",
        counter_body: "Name the move. Redirect to the claim. Don't defend yourself — defending implies the personal attack was relevant. Make the attacker explain why their point matters to the substance.",
        counter_example: "'What does my age have to do with whether the numbers add up? Either show me the error, or accept the proposal.'",
        tip: "Never engage with the personal label. Engaging treats it as legitimate. Ignore + return to the claim.",
      },
      ru: {
        title: 'Ad Hominem',
        hook: 'Он неправ из-за того, кем является. Не из-за того, что сказал.',
        body: 'Вместо атаки на аргумент атакуешь человека, который его произносит. Истинность аргумента не зависит от того, кто его сказал — но восприятие аудитории зависит. Дёшево, часто, обычно незаметно.',
        example: '«Твоя идея с бюджетом наивная — тебе всего 24». Возраст не влияет на то, складывается ли арифметика. Атака маскируется под оценку.',
        counter_hook: 'Я говорю про аргумент. Ты говоришь про меня.',
        counter_body: 'Назови приём. Верни разговор к утверждению. Не защищайся — защита делает личную атаку легитимной. Заставь атакующего объяснить, как его выпад относится к сути.',
        counter_example: '«Какое отношение мой возраст имеет к тому, складываются ли цифры? Покажи ошибку или прими предложение».',
        tip: 'Не вступай с ярлыком в дискуссию. Вступишь — признаешь его легитимным. Игнор + возврат к сути.',
      },
    },
  },
  {
    id: 'strawman',
    order: 2,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Strawman',
        hook: "You said one thing. They argued against something else. They won that argument.",
        body: "The opponent restates your position in a weaker, more extreme, or distorted form — then attacks that distortion. Audiences often don't notice the swap, and you end up defending a claim you never made.",
        example: "You: 'We should reduce sugar in school lunches.' Them: 'So you want to ban kids from eating anything fun?' The original was a moderate adjustment; the response is a caricature.",
        counter_hook: "That's not what I said. Here's what I actually said.",
        counter_body: "Name the distortion immediately. Restate your real position in one clean sentence. Force them to address the actual claim, not their version of it. Repeat until they engage with the original.",
        counter_example: "'I didn't say ban anything. I said reduce sugar. Address that — not the ban version you invented.'",
        tip: "Always restate your own position before responding. Otherwise the audience remembers their version, not yours.",
      },
      ru: {
        title: 'Соломенное чучело',
        hook: 'Ты сказал одно. Он спорил с другим. И выиграл этот спор.',
        body: 'Оппонент пересказывает твою позицию в более слабой, крайней или искажённой форме — и атакует именно её. Аудитория часто не замечает подмены, и ты в итоге защищаешь то, чего не говорил.',
        example: 'Ты: «надо снизить сахар в школьных обедах». Он: «то есть запретить детям всё вкусное?» Оригинал — умеренная корректировка; ответ — карикатура.',
        counter_hook: 'Я говорил не это. Вот что я говорил на самом деле.',
        counter_body: 'Сразу назови искажение. Пересформулируй свою настоящую позицию одним предложением. Заставь оппонента ответить на исходное утверждение, не на его версию. Повторяй, пока не вступит с оригиналом.',
        counter_example: '«Я не говорил про запрет. Я говорил про снижение. Отвечай на это — не на версию, которую ты придумал».',
        tip: 'Всегда пересказывай свою позицию до ответа. Иначе аудитория запомнит его версию, а не твою.',
      },
    },
  },
  {
    id: 'red-herring',
    order: 3,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Red Herring',
        hook: "They changed the subject. You followed.",
        body: "An irrelevant point is introduced to distract from the original argument. The new topic is often emotionally charged, so you follow it instinctively. By the time you notice, the original question is buried.",
        example: "You: 'The expense report has errors that need fixing.' Them: 'You know how hard accounting works in this company?' The errors didn't get addressed. Sympathy got introduced.",
        counter_hook: "That's a different question. I'm asking this one.",
        counter_body: "Notice the subject change. Acknowledge the new topic exists, but flag it as separate. Refuse to advance until the original is answered. Polite but unmovable.",
        counter_example: "'I hear that accounting is hard. Separate question. Right now I'm asking about errors in this specific report — those still need fixing.'",
        tip: "If you sense the topic shifted, list the original question out loud. Saying it makes the dodge visible to everyone.",
      },
      ru: {
        title: 'Отвлекающий манёвр',
        hook: 'Он сменил тему. Ты пошёл за ним.',
        body: 'Вводится нерелевантная мысль, чтобы отвлечь от исходного аргумента. Новая тема обычно эмоциональная, и ты следуешь за ней инстинктивно. К моменту осознания исходный вопрос забыт.',
        example: 'Ты: «в отчёте о расходах есть ошибки, нужно исправить». Он: «ты знаешь, как тяжело работать в бухгалтерии этой компании?» Ошибки не разобрали. Появилось сочувствие.',
        counter_hook: 'Это другой вопрос. Я задаю вот этот.',
        counter_body: 'Замечай смену темы. Признай новую существующей, но обозначь как отдельную. Не продвигайся, пока не отвечено на исходную. Вежливо, но непреклонно.',
        counter_example: '«Слышу, что в бухгалтерии тяжело. Это отдельный вопрос. Сейчас я спрашиваю про ошибки в конкретном отчёте — их всё ещё нужно исправить».',
        tip: 'Если чувствуешь сдвиг темы, проговори исходный вопрос вслух. Озвучивание делает уход видимым для всех.',
      },
    },
  },
  {
    id: 'false-dichotomy',
    order: 4,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'False Dichotomy',
        hook: "Two options. Both bad. There were always more.",
        body: "A complex situation is reduced to two mutually exclusive choices, when in reality more options exist or the choices aren't mutually exclusive. The framing forces you into a corner you didn't have to enter.",
        example: "'Either we cut the team or we miss the deadline.' Maybe a partial scope cut, a hiring sprint, or a deadline renegotiation also exists. The binary framing erased them.",
        counter_hook: "Why those two? Show me you've ruled out the others.",
        counter_body: "Refuse the binary. List two or three additional options out loud. Make the speaker defend why their two are exhaustive. The burden shifts to them.",
        counter_example: "'Cut team or miss deadline — those aren't the only options. We could renegotiate scope, or hire short-term, or shift the date by a week. Why are we only considering your two?'",
        tip: "When facing 'A or B,' immediately ask 'or what else?' The brain seizes the binary; saying the third option breaks the spell.",
      },
      ru: {
        title: 'Ложная дилемма',
        hook: 'Два варианта. Оба плохие. Всегда было больше.',
        body: 'Сложная ситуация сводится к двум взаимоисключающим вариантам, хотя на деле есть больше или они не взаимоисключающие. Фрейминг загоняет тебя в угол, в который входить не обязательно.',
        example: '«Либо сокращаем команду, либо пропускаем дедлайн». Возможно, есть частичное сокращение скоупа, экстренный найм или передоговор дедлайна. Бинарный фрейм их стёр.',
        counter_hook: 'Почему именно эти два? Покажи, что отбросил остальные.',
        counter_body: 'Откажись от бинарности. Назови вслух два-три дополнительных варианта. Заставь оппонента защищать, почему его два исчерпывают всё. Бремя смещается к нему.',
        counter_example: '«Сокращение или дедлайн — это не единственные варианты. Можем передоговорить скоуп, нанять временно, сдвинуть дату на неделю. Почему мы рассматриваем только твои два?»',
        tip: 'Когда тебе суют «А или Б», сразу спроси «а что ещё?». Мозг хватается за бинарность; озвучивание третьего варианта снимает чары.',
      },
    },
  },
  {
    id: 'slippery-slope',
    order: 5,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Slippery Slope',
        hook: "If we do this small thing, the disaster at the bottom is inevitable.",
        body: "A modest first step is portrayed as guaranteed to cause an extreme final outcome — without showing the chain. Each link in the chain is unproven; the whole chain is treated as certain because it's vivid.",
        example: "'If we let people work from home one day a week, soon the office is empty and the company collapses.' Each intermediate step has independent failure modes; the chain is asserted, not demonstrated.",
        counter_hook: "Show me each step. With evidence.",
        counter_body: "Demand the chain be made explicit. Ask for the probability of each link. Force the speaker to defend each step independently — most chains fall apart at link two or three.",
        counter_example: "'You're saying one WFH day → empty office → collapse. Three claims, three probabilities. Show me the evidence for each step, separately.'",
        tip: "Slippery slopes thrive on momentum. Stop the slide by treating each step as a separate claim that needs its own proof.",
      },
      ru: {
        title: 'Скользкий склон',
        hook: 'Сделай маленький шаг — катастрофа внизу неизбежна.',
        body: 'Скромный первый шаг подаётся как гарантия экстремального итога — без обоснования цепочки. Каждое звено цепи не доказано; вся цепь принимается как достоверная просто потому что ярко представлена.',
        example: '«Если разрешить людям один день удалёнки в неделю, скоро офис опустеет и компания развалится». У каждого промежуточного шага свои условия отказа; цепь заявлена, не продемонстрирована.',
        counter_hook: 'Покажи каждый шаг. С доказательствами.',
        counter_body: 'Потребуй сделать цепь явной. Спроси вероятность каждого звена. Заставь защищать каждый шаг отдельно — большинство цепей рассыпается на втором-третьем звене.',
        counter_example: '«Ты говоришь: один день удалёнки → пустой офис → развал. Три утверждения, три вероятности. Покажи доказательства каждого шага отдельно».',
        tip: 'Скользкий склон работает на инерции. Останови скольжение, относясь к каждому шагу как к отдельному утверждению, требующему своих доказательств.',
      },
    },
  },
  {
    id: 'appeal-to-authority',
    order: 6,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Appeal to Authority',
        hook: "An expert said it. End of discussion. Even if the expert is wrong.",
        body: "An argument is treated as proven because someone with credentials made it. Credentials are evidence about reliability — not about the specific claim. An expert outside their domain, or with a financial interest, can be confidently wrong.",
        example: "'Dr. X, a nutritionist, says this supplement works.' Dr. X may have credentials, but if she's paid by the supplement company or speaking outside her specialty, the claim still needs evidence.",
        counter_hook: "What's the evidence? Not the credentials — the data.",
        counter_body: "Distinguish 'expert says' from 'evidence shows.' Ask for the underlying study, mechanism, or data. A real expert can produce it; a name-dropper cannot.",
        counter_example: "'Great that Dr. X has the credentials. What's the actual study? I'll read it. If she's right, the data will show.'",
        tip: "Credentials are a prior, not a proof. Always trace to the underlying evidence — the gap between 'authority said' and 'data shows' is where bad claims hide.",
      },
      ru: {
        title: 'Апелляция к авторитету',
        hook: 'Эксперт сказал. Конец обсуждения. Даже если эксперт неправ.',
        body: 'Аргумент считается доказанным, потому что его сделал человек с регалиями. Регалии — это сведения о надёжности, не о конкретном утверждении. Эксперт вне своей области или с финансовым интересом может уверенно ошибаться.',
        example: '«Доктор X, нутрициолог, говорит — добавка работает». У доктора X может быть диплом, но если её спонсирует производитель или она говорит не по специальности — утверждение всё равно требует доказательств.',
        counter_hook: 'Где доказательства? Не регалии — данные.',
        counter_body: 'Разделяй «эксперт сказал» и «данные показывают». Запрашивай исследование, механизм, цифры. Настоящий эксперт даст; человек, кидающийся именами — нет.',
        counter_example: '«Хорошо, что у доктора X диплом. Какое исследование? Я прочитаю. Если она права, данные это покажут».',
        tip: 'Регалии — априорная вероятность, не доказательство. Всегда трассируй к данным — между «авторитет сказал» и «данные показывают» прячутся плохие утверждения.',
      },
    },
  },
  {
    id: 'ad-populum',
    order: 7,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Appeal to Popularity',
        hook: "Everyone believes it. Therefore it must be true.",
        body: "The popularity of a claim is treated as evidence for its truth. But popularity tracks emotional salience, social pressure, and tribal identity — not evidence. Many widely held beliefs throughout history were dead wrong.",
        example: "'Most people in the office think the new system is bad — so it must be bad.' Maybe most people haven't tried it, or are reacting to change-aversion, not the system itself. Volume of opinion ≠ accuracy of opinion.",
        counter_hook: "How many of them have actually tested it?",
        counter_body: "Distinguish 'popular' from 'verified.' Ask whether the believers have firsthand evidence or are repeating each other. Once you reveal the chain is hearsay, the popularity number stops mattering.",
        counter_example: "'Of those people who think it's bad — how many used it for two weeks? If most are repeating what they heard, we don't have an opinion poll, we have an echo.'",
        tip: "Replace 'how many think X' with 'how many independently verified X.' Almost always a much smaller number — and the only one that matters.",
      },
      ru: {
        title: 'Апелляция к большинству',
        hook: 'Все верят. Значит, правда.',
        body: 'Популярность утверждения трактуется как доказательство истинности. Но популярность отражает эмоциональную яркость, социальное давление и племенную идентичность — не доказательства. Много широко принятых убеждений в истории оказывались полностью неверными.',
        example: '«Большинство в офисе считают новую систему плохой — значит, она плохая». Может, большинство её не пробовало или реагирует на сопротивление переменам, а не на систему. Объём мнения ≠ точность мнения.',
        counter_hook: 'Сколько из них её реально тестировали?',
        counter_body: 'Разделяй «популярно» и «проверено». Спрашивай, есть ли у верящих личный опыт или они повторяют друг друга. Как только вскроешь, что цепь — слухи, цифра популярности теряет вес.',
        counter_example: '«Из тех, кто считает её плохой — кто использовал две недели? Если большинство повторяет услышанное, у нас не опрос, а эхо».',
        tip: 'Замени «сколько думают X» на «сколько независимо проверили X». Почти всегда — намного меньше. И только эта цифра имеет значение.',
      },
    },
  },
  {
    id: 'appeal-to-tradition',
    order: 8,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Appeal to Tradition',
        hook: "We've always done it this way. Therefore we should keep doing it this way.",
        body: "The age of a practice is treated as evidence for its correctness. Longevity proves a practice has survived — not that it's good. Plenty of long-standing practices were inefficient, harmful, or outright wrong, and survived for reasons unrelated to merit.",
        example: "'Our team has done weekly status reports for ten years. We can't drop them.' Ten years of doing something is evidence that it became normal — not that it's still useful.",
        counter_hook: "What problem is it solving today?",
        counter_body: "Decouple the practice from its history. Ask what current need it addresses. If the answer is 'because we did it before,' that's not a reason — it's a description.",
        counter_example: "'OK, ten years. Forget that for a second. What problem do status reports solve today, and is there a cheaper way to solve it?'",
        tip: "Tradition is a Chesterton's fence — sometimes it's there for a real reason. Demand the reason. If no one can name it, the fence wasn't load-bearing.",
      },
      ru: {
        title: 'Апелляция к традиции',
        hook: 'Мы всегда так делали. Значит, надо продолжать.',
        body: 'Возраст практики трактуется как доказательство её правильности. Долговечность доказывает, что практика выжила — не что она хороша. Множество долгих практик были неэффективными, вредными или просто неверными и выживали по причинам, не связанным с пользой.',
        example: '«У нас в команде десять лет еженедельные статус-отчёты. Не можем их убрать». Десять лет — доказательство, что это стало нормой, а не что это всё ещё полезно.',
        counter_hook: 'Какую задачу это решает сегодня?',
        counter_body: 'Отдели практику от истории. Спроси, какую текущую потребность она закрывает. Если ответ «потому что так делали раньше» — это не причина, это описание.',
        counter_example: '«Ок, десять лет. Забудь это на секунду. Какую задачу статус-отчёты решают сегодня, и есть ли способ дешевле?».',
        tip: 'Традиция — это «забор Честертона»: иногда он стоит по реальной причине. Потребуй причину. Если никто не назовёт — забор не нёс нагрузки.',
      },
    },
  },
  {
    id: 'appeal-to-nature',
    order: 9,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Appeal to Nature',
        hook: "It's natural. Therefore it's good. Hemlock is natural too.",
        body: "Something is treated as superior because it's 'natural.' But 'natural' is a vague label, not a moral category. Hemlock, asbestos, and arsenic are natural; vaccines, eyeglasses, and fire suppression are not. Nature has no morality; we project one onto it.",
        example: "'Use this herbal supplement — it's all-natural.' Toxic mushrooms are also all-natural. Naturalness tells you almost nothing about safety, efficacy, or value.",
        counter_hook: "Natural doesn't mean safe. What's the actual evidence?",
        counter_body: "Strip the word 'natural' from the claim and re-evaluate. Once 'natural' is removed, the speaker has to defend the product on its actual merits. Most can't.",
        counter_example: "'Forget natural for a moment. What does the supplement actually do, and what evidence shows it works? Lots of natural things will kill you.'",
        tip: "Replace 'natural' with 'untested' or 'unprocessed' and see if the claim still feels persuasive. Often it doesn't.",
      },
      ru: {
        title: 'Апелляция к природе',
        hook: 'Это натуральное. Значит, хорошее. Болиголов тоже натуральный.',
        body: 'Нечто считается лучшим, потому что «природное». Но «природное» — расплывчатый ярлык, не моральная категория. Болиголов, асбест и мышьяк природные; вакцины, очки и пожарная безопасность — нет. У природы нет морали; мы её на неё проецируем.',
        example: '«Принимай эту травяную добавку — всё натуральное». Ядовитые грибы тоже натуральные. Природность почти ничего не говорит о безопасности, эффективности или ценности.',
        counter_hook: 'Природное ≠ безопасное. Где доказательства?',
        counter_body: 'Убери слово «натуральное» из утверждения и переоцени. Когда оно ушло, продавцу придётся защищать продукт по его реальным свойствам. Большинство не справляется.',
        counter_example: '«Забудь на секунду про натуральность. Что добавка реально делает, и какие доказательства, что работает? Много природного убивает».',
        tip: 'Замени «натуральное» на «непроверенное» или «необработанное» и посмотри, остаётся ли утверждение убедительным. Обычно нет.',
      },
    },
  },
  {
    id: 'appeal-to-ignorance',
    order: 10,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Appeal to Ignorance',
        hook: "No one's proven it false. Therefore it's true.",
        body: "Absence of evidence is treated as evidence of absence — or vice versa. The argument exploits the fact that most things haven't been actively disproven, then claims the gap as confirmation. The burden of proof is silently flipped.",
        example: "'No one has proven this conspiracy isn't happening. So it might be.' By the same logic, no one has proven there isn't a teapot orbiting Mars. Lack of disproof is not proof.",
        counter_hook: "I don't have to disprove your claim. You have to support it.",
        counter_body: "Restore the burden of proof. The party making the positive claim defends it. Asking for evidence is not aggression; it's the default.",
        counter_example: "'I'm not going to prove you wrong about the conspiracy. You're claiming it exists — show the evidence. If you can't, the claim doesn't deserve a yes.'",
        tip: "Watch for the burden-flip in real time. The phrase 'prove me wrong' usually marks it. The correct response is 'prove yourself right.'",
      },
      ru: {
        title: 'Апелляция к незнанию',
        hook: 'Никто не опроверг. Значит, правда.',
        body: 'Отсутствие доказательств трактуется как доказательство отсутствия — или наоборот. Аргумент эксплуатирует факт, что большинство утверждений активно не опровергались, и засчитывает пробел как подтверждение. Бремя доказывания тихо переворачивается.',
        example: '«Никто не доказал, что этого заговора нет. Значит, может быть, он есть». По той же логике никто не доказал, что вокруг Марса не вращается чайник. Отсутствие опровержения — не доказательство.',
        counter_hook: 'Я не должен опровергать твоё утверждение. Ты должен его обосновать.',
        counter_body: 'Верни бремя доказывания. Утверждающий защищает свою позицию. Запрос доказательств — не агрессия, это норма.',
        counter_example: '«Я не буду опровергать твой заговор. Ты утверждаешь, что он есть — покажи доказательства. Если не можешь, утверждение не заслуживает согласия».',
        tip: 'Лови переворот бремени в реальном времени. Фраза «докажи, что я неправ» — обычно его маркер. Правильный ответ — «докажи, что ты прав».',
      },
    },
  },
  {
    id: 'appeal-to-emotion',
    order: 11,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Appeal to Emotion',
        hook: "Make them feel something. Bypass the question of whether it's true.",
        body: "Emotional manipulation is used to win agreement instead of evidence. Pity, fear, anger, disgust — they shortcut the reasoning circuit. The argument may be wrong, but it lands hard, and that's enough.",
        example: "'Just imagine the children when this policy fails — terrified, helpless.' Maybe the policy will fail; maybe it won't. The children imagery is doing the work, not the data.",
        counter_hook: "I share the feeling. Now show me the evidence.",
        counter_body: "Acknowledge the emotion is real and legitimate. Then ask what would actually be true. Refusing the emotion makes you cold; accepting it without question makes you manipulated. Validate, then redirect.",
        counter_example: "'I care about the children too. So let's look at what actually happens when this policy is in place. Is the harm real, or am I being scared into agreeing?'",
        tip: "When a feeling is doing the persuading, name the feeling out loud. Naming it doesn't make it disappear, but it stops it from being invisible.",
      },
      ru: {
        title: 'Апелляция к эмоциям',
        hook: 'Заставь их почувствовать. Минуй вопрос, правда ли это.',
        body: 'Эмоциональная манипуляция используется вместо доказательств. Жалость, страх, злость, отвращение — закорачивают рассуждение. Аргумент может быть ошибочным, но бьёт сильно, и этого достаточно.',
        example: '«Представь детей, когда эта политика провалится — напуганных, беспомощных». Может, провалится; может, нет. Образ детей делает работу, не данные.',
        counter_hook: 'Я разделяю чувство. Теперь покажи доказательства.',
        counter_body: 'Признай эмоцию реальной и легитимной. Потом спроси, что было бы правдой. Отказ от эмоции делает тебя холодным; принятие без вопросов — манипулируемым. Подтверди, потом перенаправь.',
        counter_example: '«Мне тоже не всё равно про детей. Поэтому давай посмотрим, что реально происходит при этой политике. Вред реален или меня пугают, чтобы согласиться?»',
        tip: 'Когда чувство делает работу убеждения — назови чувство вслух. Это не делает его исчезнувшим, но перестаёт быть невидимым.',
      },
    },
  },
  {
    id: 'tu-quoque',
    order: 12,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Tu Quoque',
        hook: "You do it too. So my doing it doesn't count.",
        body: "Instead of defending your action, you point out the accuser does the same. The accuser's hypocrisy doesn't actually change whether your action was right or wrong — but it shifts the audience's attention to them.",
        example: "Boss: 'You came in late three days this week.' You: 'You came in late on Tuesday.' Even if the boss did, your latenesses are still your latenesses. The boss's behavior is a separate issue.",
        counter_hook: "We can talk about me later. Right now we're talking about you.",
        counter_body: "Don't deny their counter-accusation outright (denial digs the hole). Acknowledge it might be true, separate it as a distinct issue, and bring focus back. Two wrongs don't merge into one resolved conversation.",
        counter_example: "'Maybe I do it too — fair point, we can address that. But that's a separate conversation. Right now, your three latenesses still need a response.'",
        tip: "Tu quoque is most effective when accuser and accused are familiar. Notice that the move doesn't disprove the original claim — it just postpones it forever.",
      },
      ru: {
        title: 'Ты сам такой',
        hook: 'Ты тоже так делаешь. Значит, моё не считается.',
        body: 'Вместо защиты своего действия ты указываешь, что обвинитель делает то же. Лицемерие обвинителя не меняет, было ли твоё действие правильным или нет — но смещает внимание аудитории на него.',
        example: 'Начальник: «ты опоздал три раза за неделю». Ты: «ты во вторник опоздал». Даже если опоздал — твои опоздания остаются твоими. Поведение начальника — отдельная история.',
        counter_hook: 'Про меня поговорим потом. Сейчас говорим про тебя.',
        counter_body: 'Не отрицай встречное обвинение в лоб (отрицание роет яму). Признай возможность, отдели как отдельный вопрос, верни фокус. Две неправды не сливаются в один разрешённый разговор.',
        counter_example: '«Возможно, я тоже так делаю — справедливо, обсудим. Но это отдельный разговор. Сейчас твои три опоздания всё ещё требуют ответа».',
        tip: 'Tu quoque работает между знакомыми. Замечай, что приём не опровергает исходное утверждение — он просто откладывает его навсегда.',
      },
    },
  },
  {
    id: 'no-true-scotsman',
    order: 13,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'No True Scotsman',
        hook: "Counterexample? That one wasn't real.",
        body: "When a counterexample is presented, the original claim is rescued by redefining the category to exclude it. The category becomes a moving target — anything that contradicts the claim is, by definition, not part of the category.",
        example: "'No true entrepreneur has ever taken a salary.' 'But Steve Jobs took a salary.' 'Well, no real entrepreneur takes a salary.' The definition tightened to exclude the counterexample.",
        counter_hook: "Define the category once. Don't change it when I push.",
        counter_body: "Pin the definition before discussing examples. Make the speaker commit to criteria up front. Then any redefinition mid-argument becomes visibly desperate.",
        counter_example: "'Before we list examples — give me your definition of \"real entrepreneur,\" and stick with it. If Jobs doesn't qualify, tell me why now, not after I name him.'",
        tip: "When a definition shifts under counterexamples, name the move: 'You're moving the definition, not defending it.' It collapses the trick.",
      },
      ru: {
        title: 'Не настоящий шотландец',
        hook: 'Контрпример? Этот ненастоящий.',
        body: 'Когда дают контрпример, исходное утверждение спасают, переопределяя категорию так, чтобы исключить его. Категория становится движущейся мишенью — всё, что противоречит, по определению не входит.',
        example: '«Ни один настоящий предприниматель не брал зарплату». «Но Стив Джобс брал». «Ну, настоящий предприниматель не берёт». Определение сузилось, чтобы исключить контрпример.',
        counter_hook: 'Определи категорию один раз. Не меняй, когда я давлю.',
        counter_body: 'Зафиксируй определение до примеров. Заставь оппонента сформулировать критерии заранее. Тогда любое изменение по ходу спора станет визуально отчаянным.',
        counter_example: '«До перечисления примеров — дай определение «настоящего предпринимателя» и держись его. Если Джобс не подходит, скажи почему сейчас, не после того как я его назову».',
        tip: 'Когда определение скользит под контрпримерами, назови приём: «ты двигаешь определение, не защищаешь его». Это разрушает фокус.',
      },
    },
  },
  {
    id: 'begging-the-question',
    order: 14,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Begging the Question',
        hook: "The conclusion is hidden inside the premise. The argument proves itself.",
        body: "Also called circular reasoning. The claim assumes its own conclusion is already true, then 'derives' the conclusion. The argument feels rigorous because words are moving — but the logic doesn't go anywhere.",
        example: "'This book is the best because it's a masterpiece.' Calling it a masterpiece is the same as calling it best. The reasoning loops back to itself with new vocabulary.",
        counter_hook: "Your reason is a restatement of your conclusion.",
        counter_body: "Map the argument explicitly: what's the claim? What's the evidence? If the evidence and the claim are the same idea in different words, the argument is empty. Show the loop.",
        counter_example: "'You said the book is best because it's a masterpiece. Masterpiece and best are synonyms here. What's the actual evidence — sales, reviews, originality, technique? Pick one.'",
        tip: "Restate the speaker's argument as 'X because X.' If it survives in that form, you've found the loop.",
      },
      ru: {
        title: 'Круговая аргументация',
        hook: 'Вывод спрятан внутри посылки. Аргумент доказывает сам себя.',
        body: 'Также «предвосхищение основания». Утверждение предполагает свой собственный вывод уже истинным, потом «выводит» вывод. Аргумент кажется строгим, потому что слова двигаются — но логика никуда не идёт.',
        example: '«Эта книга лучшая, потому что это шедевр». Назвать её шедевром — то же, что назвать лучшей. Рассуждение возвращается к себе с новой лексикой.',
        counter_hook: 'Твоя причина — пересказ твоего вывода.',
        counter_body: 'Распиши аргумент явно: какое утверждение? Какие доказательства? Если доказательства и утверждение — одна мысль другими словами, аргумент пуст. Покажи петлю.',
        counter_example: '«Ты сказал: книга лучшая, потому что шедевр. Шедевр и лучшая — здесь синонимы. Какое реальное доказательство — продажи, отзывы, оригинальность, техника? Выбери одно».',
        tip: 'Перескажи аргумент оппонента как «X, потому что X». Если выжил в такой форме — нашёл петлю.',
      },
    },
  },
  {
    id: 'post-hoc',
    order: 15,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Post Hoc Ergo Propter Hoc',
        hook: "Y happened after X. Therefore X caused Y.",
        body: "Latin: 'after this, therefore because of this.' Sequential events are mistaken for causal ones. Two things happening in a row is the weakest possible kind of evidence for causation — yet it's the most intuitive.",
        example: "'I started taking this supplement and got better. The supplement worked.' Or you got better because the illness ran its course, sleep, time, hydration — sequence isn't proof.",
        counter_hook: "Order isn't cause. What's the mechanism?",
        counter_body: "Demand a mechanism — how does X actually cause Y? Then ask about confounders: what else changed at the same time? If the speaker has neither, they have a coincidence, not a cause.",
        counter_example: "'You took the supplement and got better — what's the mechanism, and what else were you doing during those two weeks? Sleep, food, lower stress?'",
        tip: "When someone reports a personal cause-effect, ask 'what would have happened without X?' That counterfactual is what makes causation real.",
      },
      ru: {
        title: 'После — значит, вследствие',
        hook: 'Y случилось после X. Значит, X вызвал Y.',
        body: 'Латынь: «после этого, значит, по причине этого». Последовательность событий путают с причинной связью. Два события подряд — слабейшее возможное доказательство причинности, но самое интуитивное.',
        example: '«Начал принимать добавку — стало лучше. Добавка сработала». Или стало лучше, потому что болезнь прошла, или сон, или время, или вода — последовательность не доказательство.',
        counter_hook: 'Порядок ≠ причина. Какой механизм?',
        counter_body: 'Потребуй механизм: как именно X вызывает Y? Спроси про конфаундеры: что ещё менялось одновременно? Если у оппонента нет ни того, ни другого — у него совпадение, не причина.',
        counter_example: '«Ты принял добавку и стало лучше — какой механизм, и что ещё ты делал эти две недели? Сон, еда, меньше стресса?».',
        tip: 'Когда кто-то рассказывает личный причинно-следственный кейс, спроси «что было бы без X?». Этот контрфактический вопрос делает причинность реальной.',
      },
    },
  },
  {
    id: 'cum-hoc',
    order: 16,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Correlation ≠ Causation',
        hook: "Two things move together. One must drive the other. Or maybe a third drives both.",
        body: "Correlation is treated as causation without ruling out: reverse causation (Y causes X), common cause (Z causes both), or coincidence. Real causal claims require a mechanism and a way to test counterfactuals.",
        example: "'Ice cream sales and drowning rates rise together — ice cream causes drowning.' Both rise because of summer heat. The third variable is doing the work; the correlation is real but not causal.",
        counter_hook: "What if the cause runs the other way? Or there's a third thing?",
        counter_body: "Run the three-question test: (1) Could effect cause cause? (2) Is there a hidden third factor? (3) Is it pure coincidence? If at least one alternative is plausible, the causal claim is unsupported.",
        counter_example: "'Sales correlate with drowning. Could swimming cause ice cream cravings? Probably not. Is summer the third factor? Yes. Why are we ignoring summer?'",
        tip: "When you hear 'A correlates with B, so A causes B,' immediately list two other explanations out loud. The audience starts to see the gap.",
      },
      ru: {
        title: 'Корреляция ≠ причинность',
        hook: 'Две вещи движутся вместе. Одна должна вызывать другую. Или третья вызывает обе.',
        body: 'Корреляцию принимают за причинность без отсева: обратной причинности (Y вызывает X), общей причины (Z вызывает обе), совпадения. Настоящие причинные утверждения требуют механизма и способа проверить контрфактическую.',
        example: '«Продажи мороженого и утопления растут вместе — мороженое вызывает утопления». Обе растут из-за летней жары. Работает третья переменная; корреляция реальна, но не причинна.',
        counter_hook: 'А что если причина идёт в обратную сторону? Или есть третье?',
        counter_body: 'Тест трёх вопросов: (1) Может ли следствие быть причиной? (2) Есть ли скрытый третий фактор? (3) Это просто совпадение? Если хоть одна альтернатива правдоподобна — причинное утверждение не обосновано.',
        counter_example: '«Продажи коррелируют с утоплениями. Может, плавание вызывает желание мороженого? Вряд ли. Лето — третий фактор? Да. Почему мы игнорируем лето?».',
        tip: 'Когда слышишь «A коррелирует с B, значит A вызывает B», сразу назови вслух два других объяснения. Аудитория начинает видеть пробел.',
      },
    },
  },
  {
    id: 'hasty-generalization',
    order: 17,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Hasty Generalization',
        hook: "Three examples. A universal law.",
        body: "A small or biased sample is used to support a broad claim. The sample size is too small, or the sample isn't representative — but the conclusion confidently covers everyone. The vivid examples crowd out the math.",
        example: "'I met two rude waiters in Paris. The French are rude.' Two people from a city of two million don't tell you anything about a country of seventy million. But your memory has only the two.",
        counter_hook: "How big was the sample? How was it chosen?",
        counter_body: "Force the speaker to surface the data behind the generalization. Ask sample size, selection method, and how many counterexamples they remember. Most generalizations don't survive the audit.",
        counter_example: "'You met two waiters out of how many you encountered? Were any of them friendly? When you generalize from two to seventy million, the math is doing nothing.'",
        tip: "When you hear 'all,' 'most,' or 'always' from personal experience, ask for the count. Specifics shrink confident generalizations.",
      },
      ru: {
        title: 'Поспешное обобщение',
        hook: 'Три примера. Универсальный закон.',
        body: 'Маленькая или предвзятая выборка используется для широкого утверждения. Размер мал, или выборка нерепрезентативна — но вывод уверенно покрывает всех. Яркие примеры вытесняют математику.',
        example: '«Я встретил двух грубых официантов в Париже. Французы грубые». Два человека из двухмиллионного города ничего не говорят о стране из семидесяти миллионов. Но память хранит только этих двух.',
        counter_hook: 'Сколько было в выборке? Как ты её выбрал?',
        counter_body: 'Заставь оппонента вынести наружу данные за обобщением. Спроси размер выборки, метод отбора, сколько он помнит контрпримеров. Большинство обобщений не выдерживает аудита.',
        counter_example: '«Ты встретил двух официантов — из скольких вообще? Кто-то был приветливым? Когда ты обобщаешь с двух на семьдесят миллионов, математика не работает».',
        tip: 'Когда слышишь «все», «большинство», «всегда» из личного опыта — спроси число. Конкретика сжимает уверенные обобщения.',
      },
    },
  },
  {
    id: 'loaded-question',
    order: 18,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Loaded Question',
        hook: "Yes or no answers both confess. The question already convicted you.",
        body: "A question contains an unproven assumption that the answer is forced to accept. Whether you say yes or no, you've agreed to the premise. The damage is done at the level of the question, not the answer.",
        example: "'Have you stopped lying to your team?' Yes = you used to lie. No = you still lie. The premise — that you ever lied — sneaks in for free.",
        counter_hook: "I won't answer that. The question assumes something I never agreed to.",
        counter_body: "Refuse the binary. Surface the hidden premise out loud. Demand the premise be defended before any answer. If the speaker won't, the question dies on the table.",
        counter_example: "'You're asking if I stopped lying — that assumes I lied. I didn't. Defend the premise or ask a different question.'",
        tip: "Loaded questions thrive when you answer them. The right move is always to dismantle the question itself before saying yes or no.",
      },
      ru: {
        title: 'Нагруженный вопрос',
        hook: 'И «да», и «нет» признают вину. Вопрос уже осудил тебя.',
        body: 'Вопрос содержит недоказанное допущение, которое ответ вынужден принять. Что бы ты ни ответил — ты согласился с посылкой. Урон наносится на уровне вопроса, не ответа.',
        example: '«Ты перестал врать команде?» Да = раньше врал. Нет = всё ещё врёшь. Посылка — что ты вообще врал — проскочила бесплатно.',
        counter_hook: 'Не буду отвечать. Вопрос предполагает то, на что я не соглашался.',
        counter_body: 'Откажись от бинарности. Выведи скрытую посылку наружу. Требуй защиты посылки до любого ответа. Если оппонент не защитит — вопрос умирает на столе.',
        counter_example: '«Ты спрашиваешь, перестал ли я врать — это предполагает, что я врал. Я не врал. Защити посылку или задай другой вопрос».',
        tip: 'Нагруженные вопросы живут, пока ты отвечаешь. Правильный ход — разобрать сам вопрос до «да» или «нет».',
      },
    },
  },
  {
    id: 'genetic-fallacy',
    order: 19,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Genetic Fallacy',
        hook: "An idea is bad because of where it came from. Not because of what it says.",
        body: "An argument is dismissed (or accepted) based purely on its origin — who said it, where it appeared, what tradition it belongs to. The truth value of an idea is independent of its source. A correct claim from a hostile source is still correct.",
        example: "'You can't trust that statistic — it came from a magazine I dislike.' The magazine's reliability is a prior, but the specific number can still be checked. Source-based dismissal skips the check.",
        counter_hook: "Forget the source. Is the claim true?",
        counter_body: "Bracket the origin. Treat the claim as if it came from no one and ask whether it's accurate. If yes, accept it; the source was irrelevant. If no, your rejection has substance.",
        counter_example: "'I get that you don't trust the magazine. Set that aside. The number is X. Is X true? Verify it independently — that's the only thing that matters.'",
        tip: "Source-based reasoning is a shortcut. Sometimes useful (good prior), often wrong (true claim from bad source). Always trace to the underlying claim.",
      },
      ru: {
        title: 'Генетическая ошибка',
        hook: 'Идея плохая из-за того, откуда пришла. Не из-за того, что говорит.',
        body: 'Аргумент отвергается (или принимается) только из-за источника — кто сказал, где появилось, к какой традиции принадлежит. Истинность идеи не зависит от источника. Правильное утверждение из враждебного источника всё ещё правильное.',
        example: '«Этой статистике нельзя доверять — она из журнала, который я не люблю». Надёжность журнала — априорная вероятность, но конкретное число всё равно можно проверить. Отвержение по источнику пропускает проверку.',
        counter_hook: 'Забудь про источник. Утверждение истинно?',
        counter_body: 'Отдели источник. Отнесись к утверждению, будто оно ничьё, и спроси, точно ли оно. Если да — прими; источник был нерелевантен. Если нет — твоё отвержение содержательно.',
        counter_example: '«Понимаю, что ты не доверяешь журналу. Отложим. Цифра — X. X истинно? Проверь независимо — это единственное, что важно».',
        tip: 'Рассуждение по источнику — ярлык. Иногда полезен (хорошая априорная), часто ошибочен (истина из плохого источника). Всегда трассируй к самому утверждению.',
      },
    },
  },
  {
    id: 'composition-fallacy',
    order: 20,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Composition Fallacy',
        hook: "Each part has property X. So the whole has property X. Not always.",
        body: "Properties of components are wrongly assumed to transfer to the whole. Each brick is light; a wall of bricks is heavy. Each step is reversible; the staircase as a whole may not be. Whole behaviors emerge — they don't sum.",
        example: "'Every member of this team is talented, so the team is great.' Maybe — but team performance also depends on coordination, trust, and complementarity. Talented individuals on a misaligned team underperform.",
        counter_hook: "Show me the whole works — not just that the parts do.",
        counter_body: "Demand evidence at the system level, not just the component level. Ask about interactions, dependencies, and emergent failure modes. Talented parts in a broken system lose to mediocre parts in a good system.",
        counter_example: "'Each engineer is strong, fine. How do they work together? Show me the team's track record on cross-functional projects, not the individual resumes.'",
        tip: "When summing parts to claim a whole's property, ask 'what could go wrong only at the system level?' That's the gap composition reasoning ignores.",
      },
      ru: {
        title: 'Ошибка композиции',
        hook: 'У каждой части есть свойство X. Значит, у целого тоже X. Не всегда.',
        body: 'Свойства компонентов ошибочно переносят на целое. Каждый кирпич лёгкий; стена из кирпичей тяжёлая. Каждый шаг обратим; лестница в целом может быть нет. Целостные свойства возникают — они не суммируются.',
        example: '«Каждый член этой команды талантлив, значит, команда отличная». Может — но эффективность команды зависит ещё от координации, доверия и комплементарности. Талантливые в несогласованной команде проигрывают.',
        counter_hook: 'Покажи, что целое работает — не только части.',
        counter_body: 'Требуй доказательств на уровне системы, не только компонента. Спроси про взаимодействия, зависимости, отказы целого. Талантливые части в сломанной системе проигрывают середнякам в хорошей.',
        counter_example: '«Каждый инженер силён — ок. Как они вместе работают? Покажи историю команды на кросс-функциональных проектах, не личные резюме».',
        tip: 'Когда суммируешь части, чтобы заявить свойство целого — спроси «что может пойти не так только на системном уровне?». Это пробел, который композиция игнорирует.',
      },
    },
  },
  {
    id: 'division-fallacy',
    order: 21,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Division Fallacy',
        hook: "The whole has property X. So each part has property X. Not always.",
        body: "The reverse of composition — properties of the whole are wrongly assigned to the parts. The team is excellent; therefore each member is excellent. The forest is dense; therefore each tree is dense. Wholes have properties parts don't.",
        example: "'This company is innovative, so every employee is innovative.' Maybe a few teams drive innovation; the rest do necessary, non-innovative work. The label belongs to the system, not the average individual.",
        counter_hook: "The whole and the parts can have different properties.",
        counter_body: "Ask which specific parts carry the property and which don't. Force the speaker to distinguish system-level claims from individual-level claims. Most large generalizations across an organization don't survive that.",
        counter_example: "'The company is innovative — agreed. Which teams actually drive that? My team mostly executes; calling each of us innovative is flattery, not analysis.'",
        tip: "Whenever a system-level adjective is applied to its members, test it on yourself or one specific member. The misfit reveals the fallacy.",
      },
      ru: {
        title: 'Ошибка деления',
        hook: 'У целого есть свойство X. Значит, у каждой части тоже X. Не всегда.',
        body: 'Обратное к композиции — свойства целого ошибочно приписывают частям. Команда отличная; значит, каждый член отличный. Лес густой; значит, каждое дерево густое. У целого есть свойства, которых нет у частей.',
        example: '«Эта компания инновационная, значит, каждый сотрудник инновационный». Может, несколько команд двигают инновации; остальные делают необходимую, неинновационную работу. Ярлык — у системы, не у среднего сотрудника.',
        counter_hook: 'У целого и частей могут быть разные свойства.',
        counter_body: 'Спроси, какие конкретно части несут это свойство, а какие нет. Заставь оппонента разделить системные утверждения и индивидуальные. Большинство широких обобщений по организации не выживает.',
        counter_example: '«Компания инновационная — согласен. Какие команды реально это двигают? Моя в основном исполняет; называть каждого из нас инновационным — лесть, не анализ».',
        tip: 'Когда системное прилагательное приписывают членам, проверь его на себе или одном конкретном члене. Несовпадение раскрывает ошибку.',
      },
    },
  },
  {
    id: 'equivocation',
    order: 22,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Equivocation',
        hook: "One word. Two meanings. The argument slides between them.",
        body: "A key term shifts meaning mid-argument without being flagged. The argument depends on the slide — it's true in one meaning, false in the other, and the speaker uses both as if they were the same.",
        example: "'A feather is light. Light cannot be dark. Therefore a feather cannot be dark.' 'Light' shifts from 'low weight' to 'illumination.' The pun makes a fake syllogism look sound.",
        counter_hook: "Define the word once. Use that definition all the way through.",
        counter_body: "Identify the slippery word. Pin its meaning at the start. Replace it with the chosen definition wherever it appears in the argument. The argument either survives the substitution or collapses.",
        counter_example: "'You're using \"light\" two ways. Pick one — weight or illumination. Now restate your argument with that one meaning. If it still works, I'll consider it.'",
        tip: "Strong arguments survive a 'find-and-replace' on their key terms with rigid definitions. Equivocation never does.",
      },
      ru: {
        title: 'Подмена понятий',
        hook: 'Одно слово. Два смысла. Аргумент скользит между ними.',
        body: 'Ключевой термин меняет значение по ходу аргумента, и это не отмечается. Аргумент держится на скольжении — истинен в одном смысле, ложен в другом, и оратор использует оба как одно.',
        example: '«Перо лёгкое. Лёгкое не бывает тяжёлым. Значит, перо не бывает тяжёлым». «Лёгкое» — то «малый вес», то «освещённость». Каламбур делает фальшивый силлогизм похожим на настоящий.',
        counter_hook: 'Определи слово один раз. Используй определение до конца.',
        counter_body: 'Найди скользящее слово. Зафиксируй смысл в начале. Подставь определение везде, где оно встречается. Аргумент либо переживёт подстановку, либо рассыплется.',
        counter_example: '«Ты используешь «лёгкое» двумя способами. Выбери один — вес или освещённость. Перескажи аргумент с одним смыслом. Если всё ещё работает — обсудим».',
        tip: 'Сильные аргументы переживают «найти и заменить» ключевых терминов жёсткими определениями. Подмена — никогда.',
      },
    },
  },
  {
    id: 'moving-the-goalposts',
    order: 23,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Moving the Goalposts',
        hook: "You met their condition. They invented a new one.",
        body: "When evidence is provided, the standard required for that evidence is raised. Each time you meet the bar, the bar moves. The argument is unwinnable by design — but it looks reasonable on each individual round.",
        example: "Them: 'Show me one peer-reviewed study.' You: '[shows one]' Them: 'I meant a meta-analysis.' You: '[finds one]' Them: 'From a top-tier journal.' Each ask is technically reasonable; the pattern is fraud.",
        counter_hook: "Tell me your final standard. Then we'll see if I meet it.",
        counter_body: "Stop providing evidence on demand. Ask the speaker to write down the full standard up front: what would convince them? If they refuse, the discussion isn't real. If they commit, you can hit the standard once and be done.",
        counter_example: "'Before I find another paper — what's the complete bar? List every requirement now. If I meet that list, you accept the claim. Yes or no?'",
        tip: "Goalpost-moving dies the moment you ask for the full criteria up front. People who plan to move them refuse to commit.",
      },
      ru: {
        title: 'Передвигание ворот',
        hook: 'Ты выполнил условие. Он придумал новое.',
        body: 'Когда даны доказательства, стандарт для них поднимается. Каждый раз, когда ты добираешься до планки — она двигается. Аргумент непобедим по дизайну, но на каждом раунде кажется разумным.',
        example: 'Он: «покажи одно рецензируемое исследование». Ты: «[показываешь]». Он: «я имел в виду мета-анализ». Ты: «[находишь]». Он: «из топ-журнала». Каждый запрос вроде разумен; паттерн — мошенничество.',
        counter_hook: 'Скажи финальный стандарт. Потом проверим, выполнил ли я.',
        counter_body: 'Прекрати выдавать доказательства по требованию. Попроси оппонента записать полный стандарт сразу: что его убедит? Если откажется — обсуждение не настоящее. Если зафиксирует — ударишь по стандарту один раз и закроешь.',
        counter_example: '«Прежде чем искать следующую статью — какая полная планка? Перечисли все требования сейчас. Если выполню — принимаешь утверждение. Да или нет?»',
        tip: 'Передвигание ворот умирает в момент, когда ты просишь полные критерии заранее. Те, кто планирует двигать — отказываются фиксировать.',
      },
    },
  },
  {
    id: 'false-equivalence',
    order: 24,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'False Equivalence',
        hook: "Two things share a tiny feature. They're treated as equally bad. Or equally fine.",
        body: "Two situations differ in scale, severity, or context, but are presented as equivalent because they share one surface feature. The framing flattens differences that actually matter — and the conclusion you draw applies to both.",
        example: "'Skipping the gym one day and never going at all are both not exercising.' Technically true; consequentially absurd. The shared surface feature ('not exercising') hides the order-of-magnitude gap.",
        counter_hook: "Same surface, different scale. The difference is the whole story.",
        counter_body: "Name what's actually equal between the two cases — usually a label. Then list what's unequal: magnitude, frequency, context, intent. The unequal axes are the relevant ones; the label was decoration.",
        counter_example: "'Sure, both are \"not exercising\" — once a year and once a week aren't the same thing. The label is shared; the impact isn't. Use a measure that captures the actual difference.'",
        tip: "When two things are equated, ask 'equal in what dimension?' If the dimension is just naming, the equivalence is false.",
      },
      ru: {
        title: 'Ложная эквивалентность',
        hook: 'Две вещи имеют общую мелочь. Их считают одинаково плохими. Или одинаково нормальными.',
        body: 'Две ситуации отличаются по масштабу, серьёзности или контексту, но подаются как эквивалентные, потому что разделяют одну поверхностную черту. Фрейминг сглаживает различия, которые имеют значение — и вывод накладывается на обе.',
        example: '«Пропустить зал один раз и никогда не ходить — это всё \"не тренироваться\"». Технически правда; по последствиям абсурд. Общая поверхностная черта прячет разрыв на порядок.',
        counter_hook: 'Та же поверхность, другой масштаб. Различие — это вся суть.',
        counter_body: 'Назови, что реально одинаково в двух кейсах — обычно ярлык. Потом перечисли, что неравно: магнитуда, частота, контекст, намерение. Неравные оси — релевантные; ярлык был украшением.',
        counter_example: '«Ок, оба — «не тренироваться» — раз в год и раз в неделю не одно и то же. Ярлык общий; эффект — нет. Используй меру, которая ловит реальную разницу».',
        tip: 'Когда две вещи приравнивают, спроси «равны по какому измерению?». Если измерение — только название, эквивалентность ложная.',
      },
    },
  },
  {
    id: 'special-pleading',
    order: 25,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Special Pleading',
        hook: "The rule applies to everyone. Except this case. For special reasons.",
        body: "An exception is invented to protect a claim or person without justifying why this case is genuinely different. The exception isn't reasoned — it's needed. The justification appears only when needed.",
        example: "'Astrologers' predictions are very accurate.' 'But the test was a 50% hit rate.' 'You can't test astrology with controlled methods — it requires real-life conditions.' The exception arrived right when it was needed.",
        counter_hook: "If the exception is real, it should exist before the failure.",
        counter_body: "Ask whether the exception was stated up front, before the test. If not — and especially if it materialized only when results disagreed — it's protective, not principled. Pre-registered exceptions are valid; post-hoc ones are special pleading.",
        counter_example: "'You're saying astrology only works in real-life conditions — was that condition stated before the test, or after the test failed? Because it sounds invented to save the result.'",
        tip: "Pre-register the conditions for any claim. If exceptions emerge only after disconfirmation, they're not exceptions — they're escapes.",
      },
      ru: {
        title: 'Особое обстоятельство',
        hook: 'Правило для всех. Кроме этого случая. По специальным причинам.',
        body: 'Исключение придумывается для защиты утверждения или человека без обоснования, чем именно этот случай реально отличается. Исключение не выводится — оно нужно. Оправдание появляется только когда требуется.',
        example: '«Астрологи предсказывают очень точно». «Но в тесте процент попаданий 50%». «Астрологию нельзя проверять контролируемыми методами — требуются реальные условия». Исключение пришло точно когда понадобилось.',
        counter_hook: 'Если исключение реальное — оно должно существовать до провала.',
        counter_body: 'Спроси, было ли исключение озвучено до теста. Если нет — и особенно если оно появилось только когда результаты не сошлись — оно защитное, не принципиальное. Предзарегистрированные исключения валидны; постфактум — особое обстоятельство.',
        counter_example: '«Ты говоришь, что астрология работает только в реальных условиях — это условие было озвучено до теста или после провала? Звучит как изобретение для спасения результата».',
        tip: 'Предрегистрируй условия любого утверждения. Если исключения появляются только после опровержения — это не исключения, это побеги.',
      },
    },
  },
  {
    id: 'burden-of-proof-reversal',
    order: 26,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Burden of Proof Reversal',
        hook: "I claim X. You haven't disproven X. So X is true.",
        body: "The party making a positive claim shifts the responsibility for evidence onto the doubter. Disproving an unsupported claim is often impossible (you can't prove a teapot doesn't orbit Mars). The flip exploits that asymmetry.",
        example: "'Aliens visited earth in 1947. If you don't believe me, prove they didn't.' The original claim has no evidence; the request for evidence is redirected. By default, the unsupported claim retains the floor.",
        counter_hook: "I don't have to disprove your claim. You have to support it.",
        counter_body: "Restore the standard: positive claims require evidence. Refuse to engage in the disproof game. The default position toward unsupported claims is uncertainty, not assent.",
        counter_example: "'I'm not claiming aliens didn't visit. I'm refusing to accept that they did, until you bring evidence. Doubt isn't a position I have to defend.'",
        tip: "The phrases 'prove me wrong' or 'you can't disprove this' are signals. Always answer 'the burden is on you,' not 'fine, here's an attempt.'",
      },
      ru: {
        title: 'Переворот бремени доказывания',
        hook: 'Я утверждаю X. Ты не опроверг X. Значит, X истинно.',
        body: 'Утверждающий перекладывает ответственность за доказательства на сомневающегося. Опровергнуть необоснованное утверждение часто невозможно (нельзя доказать, что чайник не вращается вокруг Марса). Переворот эксплуатирует эту асимметрию.',
        example: '«Инопланетяне посетили землю в 1947. Если не веришь — докажи, что не посещали». У исходного утверждения нет доказательств; запрос доказательств перенаправлен. По умолчанию необоснованное утверждение остаётся на сцене.',
        counter_hook: 'Я не должен опровергать твоё. Ты должен обосновать своё.',
        counter_body: 'Восстанови стандарт: положительные утверждения требуют доказательств. Откажись играть в игру опровержений. Дефолтная позиция к необоснованным утверждениям — неопределённость, не согласие.',
        counter_example: '«Я не утверждаю, что инопланетян не было. Я отказываюсь принимать, что они были, пока нет доказательств. Сомнение — не позиция, которую я должен защищать».',
        tip: 'Фразы «докажи, что я неправ» или «ты не сможешь это опровергнуть» — сигналы. Всегда отвечай «бремя на тебе», не «ок, попытаюсь».',
      },
    },
  },
  {
    id: 'reductio-ad-hitlerum',
    order: 27,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: "Reductio ad Hitlerum",
        hook: "The bad guy did this. Therefore doing this makes you the bad guy.",
        body: "Also Godwin's law, in the limit. An idea is dismissed because someone universally despised once held it. But shared positions don't transfer guilt — and many of history's villains were vegetarians, painters, or fans of dogs.",
        example: "'Hitler supported animal welfare laws. So if you support animal welfare, you're aligned with him.' The shared specific belief carries none of the broader moral package. The association is a smear.",
        counter_hook: "Sharing one belief with anyone isn't an indictment.",
        counter_body: "Disentangle the specific claim from the figure attached to it. Note that any sufficiently common belief will overlap with bad actors somewhere. Force evaluation on the merits of the claim, not the company it allegedly keeps.",
        counter_example: "'Hitler also liked dogs. Liking dogs doesn't make me Hitler. The animal welfare claim either stands or falls on its own evidence — not on whose name you attach to it.'",
        tip: "When a comparison to a universally hated figure appears, the speaker has stopped arguing the topic. Name the move and demand the actual argument back.",
      },
      ru: {
        title: 'Reductio ad Hitlerum',
        hook: 'Этот плохой парень так делал. Значит, делая это, ты — плохой парень.',
        body: 'В пределе — закон Годвина. Идея отвергается, потому что её когда-то держал универсально ненавидимый человек. Но общие позиции не передают вину — и многие злодеи истории были вегетарианцами, художниками или любителями собак.',
        example: '«Гитлер поддерживал законы о защите животных. Значит, если ты поддерживаешь — ты с ним заодно». Общая конкретная позиция не несёт более широкий моральный пакет. Ассоциация — это клевета.',
        counter_hook: 'Совпадение одной позиции с кем угодно — не обвинение.',
        counter_body: 'Отдели конкретное утверждение от приложенной фигуры. Замечу: любое достаточно распространённое убеждение где-то пересечётся с плохими людьми. Заставь оценивать утверждение по сути, не по компании, которую ему приписывают.',
        counter_example: '«Гитлер тоже любил собак. Любовь к собакам не делает меня Гитлером. Защита животных стоит или падает на своих доказательствах — не на имени, которое ты к ней приписываешь».',
        tip: 'Когда появляется сравнение с универсально ненавидимой фигурой, оппонент перестал спорить о теме. Назови приём и потребуй настоящий аргумент обратно.',
      },
    },
  },
  {
    id: 'gish-gallop',
    order: 28,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Gish Gallop',
        hook: "Twenty bad arguments delivered fast. Refuting them takes ten times longer.",
        body: "Named after creationist Duane Gish. The strategy: dump so many superficial points that no opponent can address them all in real time. The audience confuses the volume of points with the strength of the case.",
        example: "In a debate, one side presents fifteen quick claims in two minutes. The other side has two minutes to respond. Even if they refute the strongest five, the rest stand unchallenged in the audience's memory.",
        counter_hook: "Pick three. The strongest three. Defend those, then we'll talk.",
        counter_body: "Refuse to chase every point. Force the speaker to commit to their best three claims. If they refuse, the gallop is exposed as theater. If they pick three, you've made the conversation winnable.",
        counter_example: "'You made fifteen points. I won't refute all of them — that's the trap. Pick three you're most confident in. We discuss those. The rest is volume, not substance.'",
        tip: "Volume defeats truth in real-time formats. Always ask for the speaker's best argument; their best is your floor.",
      },
      ru: {
        title: 'Гиш-галоп',
        hook: 'Двадцать плохих аргументов на скорости. Опровержение займёт в десять раз больше.',
        body: 'Назван по креационисту Дуэйну Гишу. Стратегия: набросать столько поверхностных пунктов, чтобы оппонент физически не успел разобрать все. Аудитория путает объём аргументов с силой позиции.',
        example: 'В дебатах одна сторона выдаёт пятнадцать быстрых утверждений за две минуты. У другой две минуты на ответ. Даже если опровергнут пять сильнейших — остальные остаются неоспоренными в памяти аудитории.',
        counter_hook: 'Выбери три. Самые сильные три. Защити их — потом поговорим.',
        counter_body: 'Откажись бежать за каждым пунктом. Заставь оппонента зафиксировать три лучших утверждения. Если откажется — галоп разоблачён как театр. Если выберет три — разговор стал победимым.',
        counter_example: '«Ты сделал пятнадцать пунктов. Не буду опровергать все — это ловушка. Выбери три, в которых ты уверен больше всего. Их обсудим. Остальное — объём, не суть».',
        tip: 'Объём побеждает истину в реальном времени. Всегда проси лучший аргумент оппонента; его лучшее — твой минимум.',
      },
    },
  },
  {
    id: 'cherry-picking',
    order: 29,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Cherry Picking',
        hook: "Out of a hundred data points, they picked five. The five that agree with them.",
        body: "Selecting evidence that supports the conclusion while ignoring evidence that contradicts it. The selection happens silently, so the audience sees only the agreeable data and assumes it represents the whole.",
        example: "'Three studies show this drug works.' True — but seventeen others show it doesn't. The three are real; the picture they paint isn't. Cherry-picking is honest about the part it shows and dishonest about the part it hides.",
        counter_hook: "What's the full data? Including what disagrees with you.",
        counter_body: "Demand the denominator. Ask how many studies, examples, or data points exist in total — not just the ones cited. If the speaker doesn't know, they can't responsibly draw the conclusion they're drawing.",
        counter_example: "'Three studies, OK. How many studies have looked at this question total? What did the others say? I want the ratio, not the favorable count.'",
        tip: "Always ask 'out of how many?' before accepting any list of supporting examples. Cherry-picking dies when the denominator surfaces.",
      },
      ru: {
        title: 'Сбор вишенок',
        hook: 'Из ста точек данных выбрали пять. Те, что согласны с оппонентом.',
        body: 'Выбираются доказательства, поддерживающие вывод, и игнорируются опровергающие. Отбор происходит молча, так что аудитория видит только удобные данные и считает, что они представляют всё.',
        example: '«Три исследования показывают, что препарат работает». Правда — но семнадцать других показывают, что нет. Три реальны; картина, которую они рисуют — нет. Cherry-picking честен в том, что показывает, и нечестен в том, что прячет.',
        counter_hook: 'Где полные данные? Включая то, что против тебя.',
        counter_body: 'Требуй знаменатель. Спроси, сколько исследований, примеров или точек данных всего — не только процитированных. Если оппонент не знает — он не может ответственно делать тот вывод, который делает.',
        counter_example: '«Три исследования, ок. Сколько исследований по этому вопросу всего? Что говорят остальные? Мне нужен коэффициент, не благоприятный счёт».',
        tip: 'Всегда спрашивай «из скольких?» до принятия любого списка поддерживающих примеров. Cherry-picking умирает, когда всплывает знаменатель.',
      },
    },
  },
  {
    id: 'whataboutism',
    order: 30,
    category: 'rhetorical_fallacies',
    i18n: {
      en: {
        title: 'Whataboutism',
        hook: "Yes, but what about that other bad thing? Now we have to talk about that instead.",
        body: "An accusation is deflected by raising a different — usually equally bad — issue elsewhere. The original problem isn't addressed; it's merely paired with another. Both can be true; both still need addressing — but the move is to talk about neither.",
        example: "Manager: 'The report has three errors.' You: 'What about the budget meeting last week — that had problems too.' Both might be true. The errors in the report still exist; raising the other issue doesn't fix them.",
        counter_hook: "Both can be wrong. Right now we're solving this one.",
        counter_body: "Acknowledge the second issue is real (don't dismiss). Insist on serializing — finish the original conversation before opening the second. This is the structural difference between whataboutism and a fair point.",
        counter_example: "'You're right — the budget meeting also had issues. We can address that next. Right now, the three errors in the report still need fixing — let's not skip past them.'",
        tip: "Whataboutism wants to swap topics. Defeat it by stacking topics: 'we'll do yours after mine.' Most users of the move won't accept the queue.",
      },
      ru: {
        title: 'Whataboutism (а как насчёт)',
        hook: 'Да, но что насчёт того другого плохого? Теперь будем говорить про это.',
        body: 'Обвинение отклоняется поднятием другой — обычно столь же плохой — проблемы где-то ещё. Исходная не решается; её просто соединяют с другой. Обе могут быть правдой; обе всё ещё требуют ответа — но приём в том, чтобы не говорить ни о чём.',
        example: 'Менеджер: «в отчёте три ошибки». Ты: «а как насчёт бюджетного совещания на прошлой неделе — там тоже проблемы». Оба могут быть правдой. Ошибки в отчёте всё ещё там; поднятие другой проблемы их не чинит.',
        counter_hook: 'Оба могут быть неправильны. Сейчас решаем этот.',
        counter_body: 'Признай вторую проблему реальной (не отмахивайся). Настаивай на сериализации — закончи исходный разговор до открытия второго. Это структурная разница между whataboutism и честным замечанием.',
        counter_example: '«Ты прав — на бюджетной встрече тоже были проблемы. Мы это разберём следующим. Сейчас три ошибки в отчёте всё ещё требуют ответа — не проскакиваем».',
        tip: 'Whataboutism хочет сменить тему. Побеждай его, стэкая темы: «твоё разберём после моего». Большинство применяющих не примут очередь.',
      },
    },
  },
];
